### ISSUE TITLE
The filter reset button does not work

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#496] opened 2016-05-20 14:56 UTC
The "Reset the filters" button does not seem to work. The page reloads but it does not reset the filters which were previously set.

![contao_reset_filter](https://cloud.githubusercontent.com/assets/1218766/15431716/6b351746-1eab-11e6-932d-3e3108d011ac.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment] 2016-05-23 09:23
I cannot reproduce this. It works like a charm on my system.

**Comment by leofeyer** [comment] 2016-05-23 09:26
Also see https://leofeyer.de/files/slides/2016/konferenz/#41 :)

**Comment by xchs** [comment] 2016-05-23 15:59
Did you check this only in Chrome?

**Comment by leofeyer** [comment] 2016-05-24 14:22
Not only in Chrome, but only in Webkit-based browsers. I can confirm that it does not work in Firefox on Mac OS.

**Comment by xchs** [comment] 2016-05-24 20:13
I have tested it in Chrome, Firefox and IE. In the latter two it does not work.

**Comment by leofeyer** [comment] 2016-05-28 10:31
This is due to the `<input type="image">` button, which submits `filter_reset_x` and `filter_reset_y` instead of just `filter_reset` in any browser but Chrome. It should be a real `<button>` tag anyway.

**Comment by discordier** [comment] 2016-05-28 12:08
Wow, I wasn't aware that webkit does not send with the coords. It's non standard behaviour IMO.
We used them for click regions back in the days. Thanks for pointing this out.

**Comment by leofeyer** [comment] 2016-05-28 12:39
Fixed in 889008e2383b2307e9a4c201aba0646cc8013b05.

**Closed by leofeyer** 2016-05-28 12:39 UTC
Labels: defect

**Comment by xchs** [comment] 2016-05-28 12:45
Perfect. Thanks a lot!
