### ISSUE TITLE
Frontend::getPageIdFromUrl() doesn't find an active page with app_dev.php

### ISSUE THREAD

**Issue by mbuchholz** [contao/core-bundle#289] opened 2015-06-02 18:37 UTC
The logged error is:
`No active page for page ID "app_dev.php" (http://example.domain/app_dev.php/home.html)`

If app_dev.php is used the first fragment is always "app_dev.php".
Here is a dump of the fragments array:
```
array:3 [
  0 => "app_dev.php"
  1 => "auto_item"
  2 => "home"
]
```

**Comment by leofeyer** [comment] 2015-06-08 07:52
I actually cannot reproduce this issue. What are your settings? Did you enable `prepend_locale` in the `app/config/parameters.yml` file? Did you enable `auto_item` and/or folder URLs?

**Comment by mbuchholz** [comment] 2015-06-08 08:01
I have `auto_item`and `folder Urls` enabled. `prepend_locale` is set to false. All other settings in the `app/config/parameters.yml`file are default.

**Comment by aschempp** [comment] 2015-06-08 08:30
Probably due to folder urls…

**Comment by mbuchholz** [comment] 2015-06-08 08:46
I set up a fresh installation where all settings are set to default. There is folder Urls disabled and that doesn't solve the issue.
I made a dirty workaround for me to get it running. For this reason i removed the first fragment in `Fontend::getPageIdFromUrl()` if it is 'app_dev.php'.

**Comment by leofeyer** [comment] 2015-06-08 12:48
In which line have you added the workaround? And how does `$arrFragments` look like right before you apply it?

**Comment by mbuchholz** [comment] 2015-06-08 13:19
I added it in Line [222] (https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/classes/Frontend.php#L222).
This is the dump one line before the workaround:
```
array:2 [
  0 => "app_dev.php"
  1 => "home"
]
```

**Comment by leofeyer** [comment] 2015-06-08 18:05
I still cannot reproduce the issue. Here's what `$arrFragments` looks like in line 222:

```php
array:1 [
  0 => "content-elements"
]
```

I'm closing the ticket for now. If someone else has the same problem, please leave a comment here and I'll reopen it.

**Closed by leofeyer** 2015-06-08 18:05 UTC
Labels: defect, unconfirmed
