### ISSUE TITLE
Referer URL parameter

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1028] opened 2017-08-17 22:26 UTC
Since version 4.4.3 Contao adds an referer URL parameter when logging out from the back end:
```
https://demo.contao.org/contao/login?ref=BJFDmjLr
```
The referer ID changes, of course, every time. However, this could be a problem with password managers if they are set to match the exact URL.

By the way: The same happens when the link to the back end is clicked in the install tool:
```
https://example.com/contao/login?referer=Y29udGFv
```
It is, of course, perfectly fine, if Contao adds the referer ID when you navigate in the back end. But is it really necessary to add the referer ID also when logging out from the back end?

**Comment by leofeyer** [comment] 2017-08-21 08:01
This is also caused by #1033, so I'm closing this one.

**Closed by leofeyer** 2017-08-21 08:01 UTC
Labels: defect
