### ISSUE TITLE
Page title starts with a number

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#707] opened 2017-02-15 08:25 UTC
When the page title starts with a number, the page alias gets an id in front.
e. g. page title = 1. Contao Konferenz / page alias = id-1-contao-konferenz
Is this behaviour still required or can we left out the id?

**Comment by Toflar** [comment] 2017-02-15 08:26
I think this is a leftover from our long dropped database abstraction layer. I don't see a reason why this should be needed for a page alias and I'm okay with dropping it in 4.4.

**Comment by leofeyer** [comment] 2017-02-17 14:13
I believe that the prefix is added by the `standardize()` method because HTML IDs must not start with a numeric character. I don't recall any DBAL related issues. Do you probably mean this? 

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Model.php#L829

**Comment by Toflar** [comment] 2017-02-17 14:15
No I didn't specifically mean anything like this. I just thought there was something like that veeeeery long time ago ;-)
But well, the alias is not used for HTML IDs so I'm very much okay with removing the `id-` prefix in the `generateAlias()` method.

**Comment by leofeyer** [comment] 2017-02-17 14:20
Which we obviously cannot do without breaking BC.

**Comment by Toflar** [comment] 2017-02-17 14:24
I can't see any BC here. It's just a page alias, page aliases only change when you edit the page. And honestly, I don't know any reason why one would like to have the `id-` prefix. And still, if you like it you can re-add it manually :)

**Comment by lionel-m** [comment] 2017-02-17 14:25
> I believe that the prefix is added by the standardize() method because HTML IDs must not start with a numeric character.

Yes but since HTML5, it's allowed. (http://stackoverflow.com/a/36458675)

**Comment by leofeyer** [comment] 2017-02-17 14:32
> I can't see any BC here. It's just a page alias, page aliases only change when you edit the page.

The `standardize()` method is not only used for aliases:

* https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/block/block_section.html5#L2
* https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/SectionWizard.php#L46
* https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/CheckBox.php#L122
* https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/FrontendTemplate.php#L336

> Yes but since HTML5, it's allowed.

Well, then I am fine with removing the `id-`prefix. It is still a BC break though. 😄

**Comment by Toflar** [comment] 2017-02-17 14:34
I said remove it in the `generateAlias()` method, NOT the `standardize()`!

**Comment by leofeyer** [comment] 2017-02-17 14:37
How is that supposed to work? We cannot apply `str_replace('id-', '', $alias)`, because some people might want to start their aliases with `id-`.

**Comment by leofeyer** [comment] 2017-02-17 14:38
You probably mean adding a third argument to the `StringUtil::standardize()` method, right?

**Comment by Toflar** [comment] 2017-02-17 14:41
Yeah, something like that :)

**Comment by aschempp** [comment] 2017-02-17 20:11
I think this was also related to finyByIdOrAlias which initially just casted the value to ID, pontentially finding a page ID that does not have that alias. 
Should also not be a problem since we added the is_numeric check.

**Comment by discordier** [comment] 2017-02-17 21:48
I had the same problem in Catalog back then. Have written some rather big comment back in the day. It definately was related to searching for numeric ids at the same time as searching for textual aliases.

**Comment by discordier** [comment] 2017-02-25 08:56
For the record, my comment is over [here](https://github.com/contao-catalog/catalog-core/blob/e17ffbdbef0f6a379a1a42314ab5dd9537cc7769/src/system/modules/catalog/ModuleCatalogEdit.php#L126).
My issue can be reproduced by executing the following queries against a Contao database (provided a page with ID 123 exists):
```sql
-- returns dataset with id 123
SELECT p.id, p.alias FROM tl_page p WHERE p.id='123';

-- returns dataset with id 123
SELECT p.id, p.alias FROM tl_page p WHERE p.id=123;

-- returns dataset with id 123
SELECT p.id, p.alias FROM tl_page p WHERE p.id='123-testing';

-- returns no dataset
SELECT p.id, p.alias FROM tl_page p WHERE p.id='id-123-testing';
```

As you see, all queries performing something like:
```sql
SELECT p.id, p.alias FROM tl_page p WHERE p.id='123-testing' OR p.alias='123-testing';
```
Will randomly either return the dataset with ID 123 OR the one with alias 123-testing.

**Comment by Toflar** [comment] 2017-02-27 09:28
So that's because the db truncates everything that is not a digit and then it matches. Funny. Is that due to the non-strict mode? Anyway, your `Model::findByIdOrAlias()` should not have that issue thanks to the `is_numeric()` check:

```php
// Try to load from the registry
if (is_numeric($varId) && empty($arrOptions))
{
	$objModel = \Model\Registry::getInstance()->fetch(static::$strTable, $varId);

	if ($objModel !== null)
	{
		return $objModel;
	}
}

$t = static::$strTable;

$arrOptions = array_merge
(
	array
	(
		'limit'  => 1,
		'column' => array("($t.id=? OR $t.alias=?)"),
		'value'  => array((is_numeric($varId) ? $varId : 0), $varId),
		'return' => 'Model'
	),

	$arrOptions
);

return static::find($arrOptions);
```

But can anybody tell me why the code does an `OR` query which is slower than doing the following anyway??

```diff
diff --git a/system/modules/core/library/Contao/Model.php b/system/modules/core/library/Contao/Model.php
index 515018f..d855f15 100644
--- a/system/modules/core/library/Contao/Model.php
+++ b/system/modules/core/library/Contao/Model.php
@@ -807,8 +807,10 @@ abstract class Model
 	 */
 	public static function findByIdOrAlias($varId, array $arrOptions=array())
 	{
+		$isAlias = is_numeric($varId);
+
 		// Try to load from the registry
-		if (is_numeric($varId) && empty($arrOptions))
+		if ($isAlias && empty($arrOptions))
 		{
 			$objModel = \Model\Registry::getInstance()->fetch(static::$strTable, $varId);
 
@@ -825,8 +827,8 @@ abstract class Model
 			array
 			(
 				'limit'  => 1,
-				'column' => array("($t.id=? OR $t.alias=?)"),
-				'value'  => array((is_numeric($varId) ? $varId : 0), $varId),
+				'column' => $isAlias ? "$t.alias=?" : "$t.id=?",
+				'value'  => $varId,
 				'return' => 'Model'
 			),
```

**Comment by aschempp** [comment] 2017-02-27 11:10
Probably just for lazyness, it has always been like that. I would be fine changing this. 

So an alias can start with a number, but it must never be JUST a number.

**Comment by Toflar** [comment] 2017-02-27 11:22
> but it must never be JUST a number.

Exactly. We should keep the `id-` prefix if it's only a number.

**Comment by leofeyer** [comment] 2017-03-14 15:50
Ok, so I'll adjust the code to allow non-numeric aliases starting with a number.

@Toflar Do you want to create a separate ticket/PR to change the `OR` query?

**Comment by Toflar** [comment] 2017-03-20 09:15
See https://github.com/contao/core-bundle/pull/729

**Comment by leofeyer** [comment] 2017-03-20 10:00
Thank you @Toflar.

**Comment by leofeyer** [comment] 2017-03-20 11:20
Fixed in 5ec030bc8bfd5861250efcff8e9ff5d22dfd133b.

**Comment by leofeyer** [comment] 2017-03-20 20:01
I have changed the implementation in f14eaf261c32a5d2b09dfcd94be35fcaa38fbbdd so the logic applies to the `generateAlias()` method only.

**Comment by aschempp** [comment] 2017-03-21 09:56
Unfortunately, I don't think that's gonna work. `123foo` is casted to a number when compared on database level with the `id` field and would still return wrong results!

**Comment by Toflar** [comment] 2017-03-21 10:15
Which is why we don't have the `OR` query anymore...

**Comment by leofeyer** [comment] 2017-03-21 10:58
But the query change has been assigned to Contao 4.4 (new feature). Do you want me to merge it into version 4.3.6 instead?

**Comment by aschempp** [comment] 2017-03-21 11:15
> Which is why we don't have the OR query anymore...

I know, but as said, that only applies to the core things! Extensions might still use the old query mode and rely on `standardize`…

**Comment by Toflar** [comment] 2017-03-21 11:21
No, this change should be part of 4.4!

**Comment by leofeyer** [comment] 2017-03-21 11:31
So this change is completely useless in version 4.3.6.

**Comment by leofeyer** [comment] 2017-03-21 11:32
Ok, but we can still leave it in the code base, can't we?

**Comment by leofeyer** [comment] 2017-03-21 11:37
Hm, the following does **not** work on my system:

```sql
SELECT * FROM tl_page WHERE alias='403-foo'
```

How do I reproduce the initial problem?

**Comment by leofeyer** [comment] 2017-04-28 09:40
See #729.

**Closed by leofeyer** 2017-04-28 09:40 UTC
Labels: defect
