### ISSUE TITLE
animated GIFs are not resized correctly with Imagick

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1173] opened 2017-11-05 11:08 UTC
It appears Contao (or Imagick) is unable to properly resize animated GIFs, when Imagick is available and in use. Take the following example GIF: 

![f-startup-challenge-animation](https://user-images.githubusercontent.com/4970961/32414174-87ce7f80-c221-11e7-8fcc-78fa15505982.gif)

If you put that GIF into the file manager of Contao, where only GD is available, it will look normal:

![animated-gif-gd](https://user-images.githubusercontent.com/4970961/32414178-a33a1590-c221-11e7-9f37-72b2417a3f71.png)

However, if you put that GIF into the file manager of Contao where Imagick is available, it will look like this:

![animated-gif-imagick](https://user-images.githubusercontent.com/4970961/32414179-b24c9dc8-c221-11e7-9cc6-1eb1d9aaa642.png)

The file name and path of the latter image is still 
```
assets/images/2/f-startup-challenge-animation-d8ff2dde.gif
```
which means Contao indeed processed the image and probably tried to resize it to the back end size - but the resize did not really occur for some reason.

/cc @ausi

**Comment by ausi** [comment] 2017-11-05 13:08
I was able to reproduce this behavior with Imagick. I will look into it.

**Comment by ausi** [comment] 2017-11-05 14:10
I reduced it to a simple test case, and it looks like this is an Imagine or Imagick Issue. Both, resizing:

```php
(new \Imagine\Imagick\Imagine)
	->open('path/to/animated-gif.gif')
	->resize(new \Imagine\Image\Box(100, 100))
	->show('gif');
```

and cropping:

```php
(new Imagine\Imagick\Imagine)
	->open('path/to/animated-gif.gif')
	->crop(new \Imagine\Image\Point(0, 0), new \Imagine\Image\Box(100, 100))
	->show('gif');
```

doesn’t work as documented.

I think this should be reported to [avalanche123/Imagine](https://github.com/avalanche123/Imagine).

It would be great if someone can test if this issue appears with Gmagick too.

**Comment by fritzmg** [comment] 2017-11-05 16:44
May be a related ticket: https://github.com/avalanche123/Imagine/issues/402 ?

**Comment by ausi** [comment] 2017-11-06 08:35
I don’t think so. Animated GIFs should already be supported since avalanche123/Imagine#481 was merged.

**Closed** 2017-11-07 20:23 UTC
