### ISSUE TITLE
4.5.3 Search index not getting filled

### ISSUE THREAD

**Issue by bennyborn** [contao/core-bundle#1362] opened 2018-02-09 08:18 UTC
Working on a fresh 4.5.3 installation or updating from a prior version to 4.5.3 causes the search index not to get filled anymore. I'm not entirely sure if it's a problem with the core-bundle itself or one of the dependencies. I traced the problem back to this line:

https://github.com/contao/core-bundle/blob/3cdcebbe3a68881b2b55c4d92cd333b04a04c940/src/EventListener/AddToSearchIndexListener.php#L57-L59

`$this->scopeMatcher->isFrontendMasterRequest($event)` always returns false which causes the whole thing not to index any pages at all.

I don't know about all the Symfony magic happening from there so thats were I have to quit.

**Comment by fritzmg** [comment] 2018-02-09 08:21
Duplicate of #1337

**Closed** 2018-02-09 09:43 UTC
Labels: duplicate
