### ISSUE TITLE
4.0.3 - error after installation

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#344] opened 2015-09-11 10:33 UTC
I have installed Contao 4.0.3 with Composer. No problem until the creation of a new user in the install tool.

Error:

```
 FatalErrorException in localconfig.php line 3: Parse Error: syntax error, unexpected '<'
```

In the `localconfig.php` file, there are two `<?php`:

```php
<?php

<?php

### INSTALL SCRIPT START ###
$GLOBALS['TL_CONFIG']['licenseAccepted'] = true;
$GLOBALS['TL_CONFIG']['installPassword'] = '***';
$GLOBALS['TL_CONFIG']['adminEmail'] = '***';
### INSTALL SCRIPT STOP ###
```

**Comment by leofeyer** [comment] 2015-09-11 10:36
I assume you have already tried removing the local configuration file and repeating the installation process?

**Comment by lionel-m** [comment] 2015-09-11 10:46
I have removed the second `<?php` manually...

But after that I removed the maintenance mode and it does not add the php opening tag. Only during the installation. I will reinstall to see if I can reproduce a second time.

**Comment by lionel-m** [comment] 2015-09-11 10:48
PS: The back end displays 4.0.2

![capture d ecran 2015-09-11 a 12 47 45](https://cloud.githubusercontent.com/assets/814476/9813140/5f4472ae-5883-11e5-8845-ee7c8619200b.png)

**Comment by lionel-m** [comment] 2015-09-11 10:57
I have reproduce this issue.

And there is a problem with the debugger (?)


![capture d ecran 2015-09-11 a 12 55 44](https://cloud.githubusercontent.com/assets/814476/9813291/9b0ac670-5884-11e5-8a37-2a92c42af822.png)
![capture d ecran 2015-09-11 a 12 56 03](https://cloud.githubusercontent.com/assets/814476/9813298/aa56205c-5884-11e5-8073-9bb8a600a11b.png)

**Comment by aschempp** [comment] 2015-09-15 16:22
I have stumbled upon the same issue just now. Wasen't able to understand why though…

**Comment by fritzmg** [comment] 2015-09-20 21:00
Here is another user with this problem: https://community.contao.org/de/showthread.php?59085-Contao-4-0-3-verf%FCgbar&p=384873&viewfull=1#post384873

**Comment by InitArt** [comment] 2015-09-23 14:53
Same problem here, tried with composer installation and install tool using PHP 5.6.13 and nginx 1.8

**Comment by Toflar** [comment] 2015-09-25 14:42
Confirmed. Same here.

**Comment by leofeyer** [comment] 2015-10-02 14:50
I have added a workaround in 696acfdc38309e32de3d44047abb613db5b64d0e.

The underlying problem obviously is the `Config` class writing twice into the same file. The two `persistConfig()` calls were so close behind each other that it led to a race condition.

However, I thought we had fixed this potential issue a long time ago? @contao/developers /cc

**Comment by Toflar** [comment] 2015-10-02 15:15
I cannot recall but I would've used the `LockHandler` to work around this :)

**Comment by leofeyer** [comment] 2015-10-05 18:15
Turns out it was not a race condition. Fixed in e6bc7ad02f2ff564038405847f60a8f6255d0e87.

**Closed by leofeyer** 2015-10-05 18:15 UTC
Labels: defect, up for discussion

**Comment by aschempp** [comment] 2015-10-05 19:47
So this would also be a bug in Contao 3 right? If one saved the localconfig twice it would happen?

**Comment by leofeyer** [comment] 2015-10-06 06:56
No, Contao 3 is not affected, because of [this line](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Config.php#L293), which has only been added in Contao 4 to solve the issue that you can only call `Config::save()` once in Contao 3.

**Comment by aschempp** [comment] 2015-10-06 06:59
Ah, thanks for the info.
