### ISSUE TITLE
4.5-RC1 Editing user profile results in logout

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#1248] opened 2017-12-19 10:33 UTC
If you go to the user profile in the backend and click “save” you get logged out.

**Comment by fritzmg** [comment] 2017-12-19 11:40
I can confirm the issue.

**Comment by bytehead** [comment] 2017-12-19 11:48
It's probably because of this: https://github.com/contao/core-bundle/blob/4.5/src/Resources/contao/library/Contao/User.php#L674

Maybe @aschempp fixed it in his PRs (#1232 and #1238).

**Comment by aschempp** [comment] 2017-12-19 22:11
I did not fix this…

**Comment by leofeyer** [comment] 2017-12-20 13:21
This is causing the problem:

https://github.com/contao/core-bundle/blob/63be169898f3fac599a4743a88297cedbcb54d17/src/Resources/contao/drivers/DC_Table.php#L2161-L2162

I assume that Symfony no longer authenticates our token if the user changes.

**Comment by leofeyer** [comment] 2017-12-20 13:32
Fixed in 3413ae04223fff949ad92ebdf04f2f9ee79b2db7.

**Comment by aschempp** [comment] 2017-12-20 15:04
The fix is wrong! We intentionally introduced it to notice if the user profile was changed, e.g. the user became admin or that right was removed.

The best solution I can think of is adding "isAdmin" and "groups" to the serialized properties so we can compare them…

**Comment by bytehead** [comment] 2017-12-20 15:05
`isAdmin` should already be serialized.

**Comment by leofeyer** [comment] 2017-12-20 15:36
> We intentionally introduced it to notice if the user profile was changed

And this was wrong in the first place. Changing the e-mail address or the name or the timestamp should not log out a logged in user! We must only consider the roles and the activation status.

**Comment by leofeyer** [comment] 2017-12-20 15:42
I have added the admin check in 1df3d626c6293059cecddfde0a6632e53fbc0897. Do you really want to serialize the groups, too?

**Comment by leofeyer** [comment] 2017-12-20 15:53
I have added the admin and group checks in d3f5031affb6c6624d37b050527fd099afdee163.

**Closed by leofeyer** 2017-12-20 15:53 UTC
Labels: defect
