### ISSUE TITLE
Cannot duplicate internal forward page and then change the jumpTo page

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1129] opened 2017-10-06 07:35 UTC
Steps to reproduce in the online demo:

1. Create an internal forward page and point it to any regular page in the tree
2. Duplicate that internal forward page
3. Try to adjust the target page
4. It won't work, the ajax request ends up in a 400 Bad Request

**Comment by ausi** [comment] 2017-10-06 17:18
I think this problem is related to the URL parameters `mode` and `pid`. For a just duplicated page the ajax request looks like `/contao?act=edit&do=page&id=101&mode=1&pid=100` which fails. Normal ajax requests for the picker look like `/contao?act=edit&do=page&id=101`.

**Comment by leofeyer** [comment] 2017-11-09 11:15
Here is the problem:

1. The copied page is marked as new record.
2. If you open the page picker, the page tree purges new records.
3. If you try to save the new record -> `A record with the ID "83" does not exist in table "tl_page"`

😢

**Comment by fritzmg** [comment] 2017-11-09 11:17
Same problem here: https://github.com/terminal42/contao-changelanguage/issues/132

**Comment by leofeyer** [comment] 2017-11-09 11:20
@contao/developers How can we solve this? We cannot simply disable record purging in picker mode, because it will lead to unexpected behavior if someone edits the site structure in the popup.

**Comment by Toflar** [comment] 2017-11-09 11:20
Jep, just disable all purging logic in the picker mode :)

**Comment by leofeyer** [comment] 2017-11-09 11:21
See my comment above …

**Comment by Toflar** [comment] 2017-11-09 11:22
Unexpected behaviour? Such as?

**Comment by leofeyer** [comment] 2017-11-09 11:22
New page -> go back -> the page is still there.

**Comment by fritzmg** [comment] 2017-11-09 11:27
I suppose the picker needs to know its "parent" element - which can be stored somewhere and then `DC_Table::reviseTable` would remove that element from `$new_records`.

**Comment by Toflar** [comment] 2017-11-09 11:56
I have no bloody idea how to solve that issue.

**Comment by leofeyer** [comment] 2017-11-09 13:52
I do. If an element is new (`tstamp=0`), we could pass an additional picker option, which then disables the table cleanup. WDYT?

**Comment by fritzmg** [comment] 2017-11-09 13:58
Wouldn't that still lead to the unexpected behaviour? i.e. if you create a new page within the picker and go back without saving, the page would still be there, since the table cleanup is disabled.

**Comment by leofeyer** [comment] 2017-11-09 14:01
Yes. 😢

**Comment by leofeyer** [comment] 2017-11-12 16:30
So as discussed at the Contao Camp, we have to add the page ID to the picker context and protect this page from being purged and from being displayed in the tree.

**Comment by fritzmg** [comment] 2017-11-13 08:45
Though it needs to be implemented for arbitrary data records, not just pages, does it not?

**Comment by leofeyer** [comment] 2017-11-13 17:03
Fixed in ed321e19305fe6653b28c83ca40bde2cb0cac0b0.

**Comment by leofeyer** [comment] 2017-11-14 17:06
Fixed in 1ac36e302d41802d61a88308256677c6bfb423f1 now.

**Closed by leofeyer** 2017-11-14 17:06 UTC
Labels: defect

**Comment by fritzmg** [comment] 2017-11-15 08:35
The same probably needs to be done for the general picker (https://github.com/contao/core-bundle/pull/1171).

**Comment by Toflar** [comment] 2017-11-15 08:36
Already done, I've commented yesterday.

**Comment by fritzmg** [comment] 2017-11-15 08:37
Btw. will this be back ported to Contao 3?

**Comment by Toflar** [comment] 2017-11-15 08:38
How? We have no picker like that in Contao 3?

**Comment by fritzmg** [comment] 2017-11-15 08:48
Right, I forgot this happens only with the new picker implementation.
