### ISSUE TITLE
Bug in colorbox-controls if form-stylesheet is active

### ISSUE THREAD

**Issue by balduin-kowalski** [contao/core-bundle#1188] opened 2017-11-14 14:25 UTC
If the jQuery-template j_colorbox AND the css-framework for forms are both activated, there occurs a strange behavior of the colorbox-controls on Mouseover. The reason for this are the css-definitions for „button“. It seems as if the button-definitions in the forms-stylesheet overwrite the button-definitions in the colorbox stylesheet. I suggest to change the definitions in the forms-stylesheet to something like `form button {…}` to make sure it only affects buttons in forms.

**Comment by fritzmg** [comment] 2017-11-14 14:28
Duplicate of https://github.com/contao-components/contao/pull/8

**Closed** 2017-11-14 19:21 UTC
Labels: duplicate
