### ISSUE TITLE
Search index: requested pages only get indexed in 4.4.13 when running in debug mode

### ISSUE THREAD

**Issue by martinschumann** [contao/core-bundle#1338] opened 2018-01-24 23:59 UTC
Requested pages only get indexed in 4.4.13 when running in debug mode (and maintenance mode is required as well). Occurs since ScopeMatcher checks requests for being a Contao front end master request.

**Comment by ausi** [comment] 2018-01-25 07:03
Duplicate of #1337

**Closed** 2018-01-25 07:24 UTC
