### ISSUE TITLE
alias with app_dev.php not working

### ISSUE THREAD

**Issue by gebi84** [contao/core-bundle#465] opened 2016-03-26 16:58 UTC
in contao 4.1.2 under windows with php 5.6 fcgi

if i call /home in the browser the variable $strRequest is "app_dev.php/home" but should be only "home". So no Page is matching the route.

i inserted this quick fix for me:
\vendor\contao\core-bundle\src\Resources\contao\classes\Frontend.php:71
`$strRequest = str_replace('app_dev.php/', '', $strRequest);`

**Comment by fritzmg** [comment] 2016-03-27 10:15
duplicate of #426

**Closed** 2016-04-03 18:44 UTC
Labels: duplicate
