### ISSUE TITLE
Empty page after starting the install-tool

### ISSUE THREAD

**Issue by Michael1972** [contao/core-bundle#795] opened 2017-04-27 11:42 UTC
Opening the install-tool in 4.3.9  in a local mampp-environment only shows an empty site. Checking the php-log displays the following error. Code:

```
[PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "event_dispatcher". in /Users/michael/Documents/website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:803
Stack trace:
#0 /Users/michael/Documents/website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(439): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('event_dispatche...')
#1 /Users/michael/Documents/website/vendor/contao/installation-bundle/src/Controller/InstallationController.php(125): Symfony\Component\DependencyInjection\ContainerBuilder->get('event_dispatche...')
#2 /Users/michael/Documents/website/vendor/contao/installation-bundle/src/Controller/InstallationController.php(63): Contao\InstallationBundle\Controller\InstallationController->initializeApplication()
#3 /Users/michael/Documents/website/vendor/contao/installation-bundle/src/Http in /Users/michael/Documents/website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 803]. The problem only exists in 4.3.9. 4.3.8 and 4.3.7 work as expected. 
```

**Comment by leofeyer** [comment] 2017-04-27 12:54
Did you use `/contao/install.php` or `/contao/install`?

**Comment by leofeyer** [comment] 2017-04-27 12:55
Seems to be a duplicate of contao/managed-edition#7.

**Closed by leofeyer** 2017-04-27 12:55 UTC

**Comment by Michael1972** [comment] 2017-04-27 13:21
I used /install.php. But /contao/install works. Thank you. Will this be the correct path in future, instead of /install.php?

**Comment by leofeyer** [comment] 2017-04-27 13:25
Yes.
