### ISSUE TITLE
[4.4-beta1] Inline small images in the fileTree widget

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#817] opened 2017-05-08 12:54 UTC
As we did in #636 for the thumbnail images in the file manager view, we should also inline small images in the fileTree widget, because it has the same issues:

![bildschirmfoto 2017-05-08 um 14 54 13](https://cloud.githubusercontent.com/assets/367169/25805003/3ee73f0c-33fe-11e7-925d-5894a87bf17c.png)

**Comment by leofeyer** [comment] 2017-05-15 11:13
I actually cannot reproduce the issue on my system, because Contao always generates a thumbnail – even for small images that should be inlined. 🤔

**Comment by leofeyer** [comment] 2017-05-15 13:09
Now I got it. Fixed in 2ae896c62cd8c8a31963f520a5569fc1fb5a1428.

**Closed by leofeyer** 2017-05-15 13:09 UTC
Labels: defect
