### ISSUE TITLE
Collapsing/Uncollapsing bug

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#1322] opened 2018-01-18 10:59 UTC
Here is what's happening with FF 57 on ubuntu as described in https://github.com/contao/core-bundle/issues/1303#issuecomment-356920606; from the online demo:

![peek 2018-01-18 11-48](https://user-images.githubusercontent.com/5305677/35094601-022bdbf2-fc46-11e7-951e-81419e728fa2.gif)

Clicking the second time triggers opening the item in every one of my tested scenarios. Even when doing sth like: "uncollapsing section A, uncollapsing section B, collapsing section A > triggered".

I'm opening a new issue as this has nothing to do with the UX discussion in the other ticket.

**Comment by leofeyer** [comment] 2018-01-18 11:08
Can you please post the output of the dev console?

**Comment by m-vo** [comment] 2018-01-18 11:10
There is nothing there beside the usual (and nothing clicking):

    Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.
    getAttributeNode() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen getAttribute().
mootools.min.js+mooRainbow.min.js+chosen.min.js+simplemodal.min....-247b5b15.js:1:56188

**Comment by fritzmg** [comment] 2018-01-18 11:22
Hm, I cannot reproduce the problem unter FireFox 57.0.4 on Windows 10 x64.

**Comment by m-vo** [comment] 2018-01-18 11:34
True, same for me on windows. But I noticed another difference: Double clicking the preview text (anywhere in the higlighted section) triggers the redirect as well. But only on linux. I thought this was a feature :grin:.

**Comment by leofeyer** [comment] 2018-02-21 09:30
Can anyone else on Unix reproduce this?

**Comment by dmolineus** [comment] 2018-02-21 16:19
I cannot reproduce it with Firefox 58.0.2 (64bit) using Manjaro Linux.

**Comment by leofeyer** [comment] 2018-03-20 08:34
I'm closing this as it does not seem to be reproducible.

**Closed by leofeyer** 2018-03-20 08:34 UTC
Labels: defect, help needed
