### ISSUE TITLE
Don't delete incomplete and unrelated records (revise table) in the dca picker

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1219] opened 2017-12-04 17:25 UTC
When selecting child table records in the dca picker (e.g. a news article in the hyperlink content element) the call of the reviseTable method will delete newly created records (e.g. a news article created in the meantime by another user).

In my case, even a 400 error will be returned if the corresponding language page is selected while creating a new entry.

The reviseTable method must not be called in the dca picker:
```php
# src/Resources/contao/drivers/DC_Table.php
@@ public function showAll()

    //...

    if (!\Input::get('popup'))
    {
        $this->reviseTable();
    }

    // ...
```

**Comment by aschempp** [comment] 2017-12-04 17:27
`reviseTable` does never delete records from other users, it only deletes your records (based on your session data). However, this issue for current user should be fixed in the latest Contao version, are you using the latest version?

**Comment by agoat** [comment] 2017-12-04 17:38
You're right. Only incomplete records with the id from the 'new_records' session bag are deleted. So my example with another user is wrong. 

> However, this issue for current user should be fixed in the latest Contao version, are you using the latest version?

Yes, always during development (contao 4.4.8).

The reviseTable method is called when a record list is shown in the dca picker. 
So if I create a new record and then try to select another (e.g. language related) record from the same table with the dca picker, the showAll method calls the reviseTable method and my new record will be deleted from the database and the selected record can not saved to the current (new) record in the AJAX request.

**Comment by ausi** [comment] 2017-12-05 07:32
I think this should have been fixed with 1ac36e302d41802d61a88308256677c6bfb423f1

**Comment by leofeyer** [comment] 2017-12-05 07:34
It sure should. @agoat Does the issue occur in the online demo, too?

**Comment by fritzmg** [comment] 2017-12-05 08:44
I was not able to reproduce this. See this screenshot of the dca picker within a hyperlink content element:

![nr](https://user-images.githubusercontent.com/4970961/33597818-da9d2914-d9a0-11e7-8550-c0e9b1a4f94d.png)

I am able to select and save a news item, that was created by a different user and not saved yet.

**Comment by agoat** [comment] 2017-12-05 08:45
> It sure should. @agoat Does the issue occur in the online demo, too?

I cannot simulate this in the online demo because I stumbled over this when using my own picker class. But you are right, it's fixed as @ausi mentioned. If I use the `preserveRecord` attribute in the picker provider, the currenttly edited new record will not be deleted. 
The fix was implemented after setting up my own class and I didn't realized that this is relevant also outside the pageTree widget.

And btw. I didn't think of creating a page inside the picker, so my idea above wouldn't have worked.

**Closed** 2017-12-05 08:45 UTC

**Comment by agoat** [comment] 2017-12-05 08:49
> I am able to select and save a news item for the URL target, which was created by a different user and not saved yet.

This may be a different topic, but I think there shouldn't be new unsaved records from other users that can be selected with the picker (perhaps the other user decides to go back without saving).
