### ISSUE TITLE
Clear cache after installation tool

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#347] opened 2015-09-15 16:40 UTC
The installation tool does not clear the container cache. 

In my case I initially opened the frontend page which got me an "incomplete installation" message. The container was built to generate that message. I then went into the install tool and added the database details. However, they were never loaded due to the cache.

**Comment by leofeyer** [comment] 2015-10-06 09:23
Will this change if the install tool runs in dev mode?

**Comment by aschempp** [comment] 2015-10-06 09:25
I don't think so …

**Comment by leofeyer** [comment] 2015-10-16 08:24
I'm actually not able to reproduce the issue. Opening the front end gave me an "incomplete installation" message and the "prod" cache was generated. Then after completing the install tool, I went back to the front end and it gave me a "no root page found" error. I did not clear the cache though.

**Comment by aschempp** [comment] 2015-10-16 08:25
You agree that does not really make sense, right?

**Comment by leofeyer** [comment] 2015-10-16 08:26
I have tried it twice with the same result.

**Comment by leofeyer** [comment] 2015-10-16 12:24
Ok, I didn't remove the `parameters.yml` file. My bad :(

**Comment by leofeyer** [comment] 2015-10-19 13:43
Even with the `parameters.yml` file removed, I cannot reproduce the issue. If there is no `parameters.yml` file, the front end will die with an error message:

```
Uncaught exception 'InvalidArgumentException' with message 'The file "parameters.yml" does not exist 
```

At this point, there are **no cache** files being generated. So what are the exact steps to reproduce this?

**Comment by aschempp** [comment] 2015-10-20 07:02
I'm pretty sure I installed Contao using `composer create-project`. Therefore the `parameters.yml` must have been created. But the `localconfig.php` was not. I opened the frontend, and the container was build. But maybe I did not enter valid database parameters in Composer but wanted to use the install tool. Which points me to another problem: What if the DB details are changed in the install tool? Again, the container is not deleted and it would never be applied?

**Comment by leofeyer** [comment] 2015-10-20 08:04
You cannot change the DB details. Once the `parameters.yml` file is written, the install tool does not touch it anymore.

**Comment by aschempp** [comment] 2015-10-20 08:10
Uhm, why would that make sense? I mean it was not like that previously, right?

**Comment by leofeyer** [comment] 2015-10-20 08:38
The install tool does the same as the Incenteev handler. Once the file has been written, you cannot change the DB credentials on the command line either.

**Comment by aschempp** [comment] 2015-10-21 07:13
hmm, then that's a new behavior I was not aware of. It did work in my case though, so my assumption about existing `parameters.yml` must be wrong.

**Comment by leofeyer** [comment] 2015-10-26 08:27
So what shall I do with the ticket now?

**Comment by aschempp** [comment] 2015-10-26 09:33
Honestly, I still think it would be correct to delete the cache when the install tool is executed… It won't harm and prevents potential issues.

**Comment by Toflar** [comment] 2015-10-26 17:42
Huge :+1: from me, this just cost me another hour of useless debugging.

**Comment by leofeyer** [comment] 2015-10-26 18:59
@Toflar What was the issue?

**Comment by Toflar** [comment] 2015-10-27 08:15
I use a deployment script that obviously deploys the cache as well. The install tool kept asking me for my DB credentials as the local ones do not match the deployment server ones because the container is cached. There are numerous problems that might occur with caching and there's no point to cache anything in the install tool.

**Comment by leofeyer** [comment] 2015-10-28 15:09
As discussed on Mumble, the install tool should always clear the dev cache and all caches when the `parameters.yml` file is written.

**Comment by leofeyer** [comment] 2015-10-30 12:56
Fixed in contao/installation-bundle@5749448a100f5fd6e41471836d5aaf307b311315.

**Closed by leofeyer** 2015-10-30 12:56 UTC
Labels: defect, up for discussion

**Comment by aschempp** [comment] 2015-10-30 13:05
Uhm, shouldn't we actually run the `cache:clear` command? We don't know what the cache contains…

**Comment by leofeyer** [comment] 2015-10-30 13:22
Nope. First, the command does [the same](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L107) and second, the command only clears **one** cache (e.g. `dev`) and we need to clear **all** caches.

**Comment by aschempp** [comment] 2015-10-30 13:25
That’s true, but we don’t know if there are other listeners that need to clear cache? Somewhere else than the app/cache folder?

**Comment by leofeyer** [comment] 2015-10-30 13:30
Feel free to adjust the routines to whatever you think is necessary.
