### ISSUE TITLE
Windows compatibility issues

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#208] opened 2015-04-15 15:04 UTC
On my local system under Windows 7 x64 and XAMPP 1.8.3 (PHP 5.5.11) the Contao 4.0.0.-beta1 installation via `composer create-project contao/standard-edition contao4 4.0.0-beta1` fails, or rather the `app/console` command `contao:symlinks` fails with the message
```
[Symfony\Component\Filesystem\Exception\IOException]
Failed to create symbolic link from "../../C:\xampp\htdocs\contao4\vendor\contao\core-bundle\src/Resources/contao/themes\flexible" to "C:\xampp\htdocs\contao4/system/themes/flexible".
```
Only the theme symlink fails initially, the other symlinks before are successfully generated by Symfony. The problem seems to be the leading `'../../'` which creates a path like `../../C:\xampp\htdocs\…`. When those are removed from 
```php
$this->symlink("../../$path", 'system/themes/' . basename($path), $rootDir, $output);
```
then the symlink is created successfully. However, all following symlinks cannot be generated as well, i.e.
```
$this->symlink('../assets', 'web/assets', $rootDir, $output);
$this->symlink('../../system/themes', 'web/system/themes', $rootDir, $output);
$this->symlink('../app/logs', 'system/logs', $rootDir, $output);
```
Though I haven't figured out yet why.

**Comment by bezin** [comment] 2015-04-15 15:08
I have the exact same issue on Windows 8.1 / Apache 2.4.9 / PHP 5.5.12.

**Comment by leofeyer** [comment] 2015-04-16 15:22
It seems that the absolute paths is not replaced here:

https://github.com/contao/core-bundle/blob/develop/src/Command/SymlinksCommand.php#L140

Can you debug this?

**Comment by fritzmg** [comment] 2015-04-16 16:09
Ah, yes it's because of the forward slash of `"$rootDir/"`. On Windows, `$rootDir`will be:
```
C:\xampp\htdocs\contao4
```
`$theme->getPathname()` will be:
```
C:\xampp\htdocs\contao4\vendor\contao\core-bundle\src/Resources/contao/themes\flexible
```
`str_replace` will search for:
```
C:\xampp\htdocs\contao4/
```
which is not present.

Maybe you could use `$rootDir . DIRECTORY_SEPARATOR` instead, but isn't there a better solution to these kinds of problems?

**Comment by fritzmg** [comment] 2015-04-16 16:16
Hm, ok, even with the change I get
```
[Symfony\Component\Filesystem\Exception\IOException]
Failed to create symbolic link from "../../vendor\contao\core-bundle\src/Resources/contao/themes\flexible" to "C:\xampp\htdocs\contao4/system/themes/flexible".
```
If I remove the `../../` again from `"../../$path"` it will work again. Why are the `../../` necessary in the first place?

**Comment by bytehead** [comment] 2015-04-16 16:19
@fritzmg then it's probably now related to #215...

**Comment by bytehead** [comment] 2015-04-16 16:21
Does it work with the change in e907f1449c7ebd1f550f76d99ea9e3f27bcb704a?

**Comment by fritzmg** [comment] 2015-04-16 16:28
> Does it work with the change in e907f14?

No. `symlinkThemes` does not use `relativeSymlink`.

**Comment by bytehead** [comment] 2015-04-16 16:30
You're right. `DIRECTORY_SEPARATOR` is some kind of wrong...

**Comment by bytehead** [comment] 2015-04-16 16:37
The `str_replace` on [line 140](https://github.com/contao/core-bundle/blob/develop/src/Command/SymlinksCommand.php#L140) should use the `DIRECTORY_SEPARATOR`. 

(see also http://alanhogan.com/tips/php/directory-separator-not-necessary)
> (Note that DIRECTORY_SEPARATOR is still useful for things like explode-ing a path that the system gave you. ...)

**Comment by leofeyer** [comment] 2015-04-16 17:51
It still should not be necessary to use `DIRECTORY_SEPARATOR` …

**Comment by leofeyer** [comment] 2015-04-16 18:25
Does it work if you change line 140 to the following?

```php
$path = str_replace($rootDir . DIRECTORY_SEPARATOR, '', $theme->getPathname());
```

**Comment by fritzmg** [comment] 2015-04-16 18:30
I already tried that here https://github.com/contao/core-bundle/issues/208#issuecomment-93775626
But it doesn't matter, the problem is still `../../$path` later on. Even if the root directory does not get removed from the path, the problem is only the relative path used in
```php
$this->symlink("../../$path", 'system/themes/' . basename($path), $rootDir, $output);
```

**Comment by leofeyer** [comment] 2015-04-16 18:36
It is supposed to be a relative symlink: "go two directories up (from `/web/themes` to `/`) and then add the path (from `/` to `/system/themes`)".

**Comment by leofeyer** [comment] 2015-04-16 18:38
Could be [this](http://php.net/symlink#97605):

> Symlinks on windows  are created by Symlink() which accept only absolute paths  but not relative paths .relative paths on windows are not supported for symlinks

:(

**Comment by fritzmg** [comment] 2015-04-16 18:51
> It is supposed to be a relative symlink: "go two directories up (from /web/themes to /) and then add the path (from / to /system/themes)".

Hm, yes, but in case of the themes, the path generated by Symlinks::symlinkThemes still seems weird to me. Even if you remove the root directory, the code will want to generated a symlink from
```
../../vendor\contao\core-bundle\src/Resources/contao/themes\flexible
```
to
```
system/themes/flexible
```
That's what I do not understand. The leading `../../` would point outside the root directory, or am I missing something?



> Could be this:
> 
>     Symlinks on windows are created by Symlink() which accept only absolute paths but not relative paths .relative paths on windows are not supported for symlinks
> 
> :(

No, I just tried, relative symlinks work, in general. However, the problem is, that all these source paths:
```php
$this->symlink('../assets', 'web/assets', $rootDir, $output);
$this->symlink('../../system/themes', 'web/system/themes', $rootDir, $output);
$this->symlink('../app/logs', 'system/logs', $rootDir, $output);
```
simply do not exist

**Comment by leofeyer** [comment] 2015-04-16 18:52
> That's what I do not understand. The leading `../../` would point outside the root directory, or am I missing something?

They are not pointing outside the root directory.

```
system/themes/
web/system/themes -> ../../system/themes
```

**Comment by fritzmg** [comment] 2015-04-16 19:01
Aaaah, now I get it. Indeed, Windows does not support relative symlinks... well, it does, in a way - but not as expected. I'll try to explain:

If you do this on Linux
```php
$this->symlink('../app/logs', 'system/logs', $rootDir, $output);
```
it will create a symlink at the location `system/logs` and the symlink points to `../app/logs` relative to that location, as you expect.

If you do the same in Windows, the symlink creation will fail with the message
```
[Symfony\Component\Filesystem\Exception\IOException]
Failed to create symbolic link from "../app/logs" to "C:\xampp\htdocs\contao4/system/logs".
```
as already said. But now comes the weird part:

If you do __this__ on Windows:
```php
$this->symlink('../contao4/app/logs', 'system/logs', $rootDir, $output);
```
(`contao4/` is the folder that contains the Contao installation) it will __successfully__ create a symlink at the `system/logs` location, however, the symlink will be invalid, since it points to `../contao4/app/logs`.

o_0

**Comment by leofeyer** [comment] 2015-04-16 19:04
That does not really make sense, does it?

**Comment by fritzmg** [comment] 2015-04-16 19:20
Yeah, indeed it does not. The reason I tried it at all is that I misunderstood the `$source` parameter of the `SymlinksCommand::symlink` function. I thought the path would have to be relative to the current root folder or working directory. That's why I tried `../contao4/app/logs`, because that would be a valid location relative to the root directory (`../` steps out of the root directory, and `contao4/` back in).

I am currently trying to test the `symlink` function of PHP to see what is going on.

**Comment by leofeyer** [comment] 2015-04-16 19:22
Never mind. We just have to use absolute links on Windows.

**Comment by fritzmg** [comment] 2015-04-16 19:46
I think I found the problem, within PHP. PHP's symlink function checks, if the first parameter (`$target` - `topath`) does in fact exist: https://github.com/php/php-src/blob/fc33f52d8c25997dd0711de3e07d0dc260a18c11/ext/standard/link_win32.c#L169
```C
if ((attr = GetFileAttributes(topath)) == INVALID_FILE_ATTRIBUTES) {
		php_error_docref(NULL, E_WARNING, "Could not fetch file information(error %d)", GetLastError());
		RETURN_FALSE;
}
```
However, the Windows function `GetFileAttributes` expects the path to be either absolute or __relative to the working directory__. But that's a problem of course if you are using a relative symlink - the symlink will be relative to the `$source`'s directory, not the working directory, and thus this call will always fail with the `Could not fetch file information` error, when you are using an otherwise valid relative file path.

Relative symlinks would work under Windows in principle - it's just that there is a bug in PHP's symlink function, that prevents this - from my analysis.

But in any case, yes, we have to stick with absolute links on Windows for now...

**Comment by leofeyer** [comment] 2015-04-17 06:40
Thanks for the detailed explanation.

**Comment by fritzmg** [comment] 2015-04-17 07:10
I've also made a bug report on php.net: https://bugs.php.net/bug.php?id=69473

**Comment by leofeyer** [comment] 2015-04-17 10:07
Should be fixed in 77c1c106110aaf75152be5deccdc03f3ea093393. Please test and give feedback :)

**Comment by fritzmg** [comment] 2015-04-18 15:50
@leofeyer [SymlinksCommand.php#L139](https://github.com/contao/core-bundle/blob/77c1c106110aaf75152be5deccdc03f3ea093393/src/Command/SymlinksCommand.php#L139) still contains
```php
$path = str_replace("$rootDir/", '', $theme->getPathname());
```
instead of
```php
$path = str_replace($rootDir . DIRECTORY_SEPARATOR, '', $theme->getPathname());
```
Thus the theme symlinks still fail on windows:
```
  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create symbolic link from "C:\xampp\htdocs\contao4/C:\xampp\htdocs\contao4\vendor\con
  tao\core-bundle\src/Resources/contao/themes\flexible" to "C:\xampp\htdocs\contao4/system/themes
  /flexible".
```

**Comment by leofeyer** [comment] 2015-04-18 19:21
Really? I have made the necessary changes in e023e7b9a70a9229296479f62f7d16265283d2b9 and realized that half of them also affect Contao 3. So how does Contao 3 work at all on your machine?

**Comment by fritzmg** [comment] 2015-04-18 19:22
I don't know :). Can you give me an example in Contao 3? Then I can check what is going on.

**Comment by leofeyer** [comment] 2015-04-18 19:28
Just look at my changes in e023e7b9a70a9229296479f62f7d16265283d2b9. E.g.

 - `BackendInstall::importExampleWebsite()`
 - `DC_Folder::delete()`
 - `DC_Folder::generateTree()`
 - `Dbafs::addResource()`
 - `Filter\SyncExclude::accept()`
 - `Folder::getHash()`
 - `ModuleSearch::compile()`
 - `FileSelector::renderFiletree()`

All of them are using `TL_ROOT . '/', so I wonder why it is working.

**Comment by fritzmg** [comment] 2015-04-18 19:41
You are right. I have skimmed over the Contao 3 code and there are a few places, where the root directory of the Contao installation + `'/'` is (supposed to be) removed from an absolute path string - and it does indeed not work on Windows for the same reason. However, none of these instances seem to have any severe effect on the functionality of Contao on Windows. It's mostly used for logging and the like.

One example: [functions.php#L64](https://github.com/contao/core/blob/support/3.2/system/helper/functions.php#L64) - on Windows, you always see the full path here - since `str_replace(TL_ROOT . '/', '', …)` has no effect.

Some extensions are affected as well.

**Comment by leofeyer** [comment] 2015-04-19 18:28
Then we should back port the changes to Contao 3. Fixed in 32537a8e84b406dbaed89df15b9d1961bc354f2b.

**Comment by leofeyer** [comment] 2015-06-02 14:02
Ok, so this did not work so well: contao/core#7847

I've spent some more time debugging and I found out that we are passing the `FilesystemIterator::UNIX_PATHS` flag to the directory iterators, therefore everything works fine in Contao 3.5. The Symfony finder, however, does not automatically convert the directory separator (and it cannot be configured to do so either?), therefore we have to use `DIRECTORY_SEPARATOR` wherever we use the finder.

**Comment by fritzmg** [comment] 2015-06-04 10:14
There is a similar problem to these issues in `Dbafs::addResource(…)`. Look at the [following code](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Dbafs.php#L54):
```php
// The resource does not exist or lies outside the upload directory
if ($strResource == '' || strncmp($strResource,  $strUploadPath, strlen($strUploadPath)) !== 0 || !file_exists(TL_ROOT . '/' . $strResource))
{
    echo "foo";
    throw new \InvalidArgumentException("Invalid resource $strResource");
}
```
If `$strResource` happens to contain _backward_ slashes instead of _forward_ slashes, for example
```
files\syncCto_backups\database\2015-06-04_1152_DB-Backup.zip
```
The condition
```php
strncmp($strResource,  $strUploadPath, strlen($strUploadPath)) !== 0
```
will fail, because it compares `files\` with `files/`.

This problem currently arises in the newsest syncCto version (see menatwork/syncCto#236), because syncCto happens to pass the file path to `Dbafs::addResource(…)` with backward slashes instead of forward slashes.

**Comment by leofeyer** [comment] 2015-06-08 12:04
Fixed in 3261c642dcc99c53bca773c8cd3e3d55428da1eb.

**Comment by fritzmg** [comment] 2015-06-08 12:05
Will this also be backported to Contao 3.5?

**Comment by leofeyer** [comment] 2015-06-08 12:17
Yes.

**Comment by leofeyer** [comment] 2015-06-08 12:35
Back-ported in contao/core@d01d94fca33b7582b26c861722aeb2abd72e5f86.

**Comment by fritzmg** [comment] 2015-08-05 22:40
This problem is back in Contao 4.0.2, or at least when installing Contao with the new `web/install.php` script. If you run this new Install Tool under Windows, the following error will occur:
```
Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to create symbolic link from "C:/xampp/htdocs/contao-4.0.2/C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src/Resources/contao/themes\flexible" to "C:/xampp/htdocs/contao-4.0.2/system/themes/flexible".' in C:\xampp\htdocs\contao-4.0.2\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:314 
Stack trace: 
#0 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(168): Symfony\Component\Filesystem\Filesystem->symlink('C:/xampp/htdocs...', 'C:/xampp/htdocs...') 
#1 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(128): Contao\CoreBundle\Command\SymlinksCommand->symlink('C:\\xampp\\htdocs...', 'system/themes/f...') 
#2 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(77): Contao\CoreBundle\Command\SymlinksCommand->symlinkThemes() 
#3 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Co in C:\xampp\htdocs\contao-4.0.2\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 314
```
This time the problem is the other way around, sort of. For instance, in `symlinkThemes` the variable `$this->rootDir` will be
```
C:/xampp/htdocs/contao-4.0.2
```
and `$theme->getPathname()` will be
```
C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src/Resources/contao/themes\flexible
```
which will cause
```php
str_replace($this->rootDir . DIRECTORY_SEPARATOR, '', $theme->getPathname());
```
not to remove the rootDir from the theme's pathname, since it will be
```php
str_replace('C:/xampp/htdocs/contao-4.0.2\\', '', 'C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src/Resources/contao/themes\flexible');
```

**Comment by fritzmg** [comment] 2015-08-06 06:59
just fyi
```php
$this->container->getParameter('kernel.root_dir')
```
will always return forward slashes: https://github.com/symfony/symfony/blob/v2.7.3/src/Symfony/Component/HttpKernel/Kernel.php#L355

Whereas Symfony\Component\Finder, which is used here:
```php
$themes = $this->getContainer()->get('contao.resource_finder')->findIn('themes')->depth(0)->directories();
…
$path = str_replace($this->rootDir . DIRECTORY_SEPARATOR, '', $theme->getPathname());
```
seems to either return backward _or_ forward slashes, depending on the OS.

Maybe it's best to write a String utility function to normalize paths (i.e. always convert `\` to `/`). Then you could also omit the `DIRECTORY_SEPARATOR` constant.

**Comment by leofeyer** [comment] 2015-08-06 08:46
This seems to be a Symfony issue: https://github.com/symfony/symfony/issues/15474

I'll add a workaround to the installation-bundle.

**Comment by leofeyer** [comment] 2015-08-06 08:57
Fixed in contao/standard-edition@30d06354942129250296798bf683903a5b1c35ee.

**Comment by fritzmg** [comment] 2015-08-08 21:49
On Windows, the /install.php still generates Fatal Errors because the generated symlinks are not detected as symlinks: 
```
Fatal error: Uncaught exception 'LogicException' with message 'The symlink target "system/themes/flexible" exists and is not a symlink.' in C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php:204
Stack trace:
#0 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(158): Contao\CoreBundle\Command\SymlinksCommand->validateSymlink('vendor\\contao\\c...', 'system/themes/f...')
#1 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(128): Contao\CoreBundle\Command\SymlinksCommand->symlink('vendor\\contao\\c...', 'system/themes/f...')
#2 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(77): Contao\CoreBundle\Command\SymlinksCommand->symlinkThemes()
#3 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php(57): Contao\CoreBundle\Command\SymlinksCommand->generateSymlinks()
#4 C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\AbstractLockedComm in C:\xampp\htdocs\contao-4.0.2\vendor\contao\core-bundle\src\Command\SymlinksCommand.php on line 204
```

```php
is_link($this->rootDir . '/' . $target)
```
returns false, even though
```
C:\xampp\htdocs\contao-4.0.2/system/themes/flexible
```
is in fact a `<SYMLINKD>`:
```
 Directory of C:\xampp\htdocs\contao-4.0.2\system\themes

08.08.2015  23:42    <DIR>          .
08.08.2015  23:42    <DIR>          ..
06.08.2015  00:26                57 .gitignore
08.08.2015  23:42    <SYMLINKD>     flexible [C:\xampp\htdocs\contao-4.0.2/vendor\contao\core-bundle
\src/Resources/contao/themes\flexible]
               1 File(s)             57 bytes
               3 Dir(s)  29.926.965.248 bytes free
```

**Comment by leofeyer** [comment] 2015-08-09 18:09
Are you sure? `is_link()` should recognize `<SYMLINKD>`. It just cannot handle junctions.

**Comment by fritzmg** [comment] 2015-08-09 18:32
I know, but it returns false for these symlinks for some reason.

**Comment by leofeyer** [comment] 2015-08-09 18:52
This sounds like a problem on your machine?

**Comment by fritzmg** [comment] 2015-08-10 14:21
Well at least someone else is running into the same problem: https://community.contao.org/de/showthread.php?58543-Contao-4-Installation-XAMPP&p=380294&viewfull=1#post380294

I am on vacation right now, so I can't analyse it yet.

**Comment by leofeyer** [comment] 2015-08-11 08:23
Which Windows version are you using?

**Comment by fritzmg** [comment] 2015-08-11 08:27
Still Windows 7 x64, the system is the same as in the first post in this issue.

**Comment by jamesdevine** [comment] 2015-08-12 16:16
I'm also having the same problem on Windows 10 with the latest install tool + Contao 4.0.2 on WAMP, PHP 5.5.12. Exactly as described above.

**Comment by leofeyer** [comment] 2015-08-13 10:13
I am trying to debug the issue, but I just don't succeed. The error message is `symlink(): Could not fetch file information(error 3)`. There are other people out there with exactly the same problem:

http://stackoverflow.com/questions/26600247/how-to-make-windows-symlinks-work-with-mod-php

**Comment by leofeyer** [comment] 2015-08-23 19:51
There is a similar issue here: https://github.com/contao-community-alliance/composer-plugin/issues/34

**Comment by gerritlo** [comment] 2015-08-26 05:47
Is there a workaround to fix it and get contao 4 running under windows?

**Comment by fritzmg** [comment] 2015-08-26 05:50
You could remove the `is_link` conditin in the `validateSymlink` function.

**Comment by fritzmg** [comment] 2015-08-28 14:13
There might also be an issue with the automatic symlink generation for the files folder: https://community.contao.org/de/showthread.php?58872-Bilder-werden-im-Frontend-nicht-angezeigt
However, I was unable to debug it yet, due to the current problem.

**Comment by leofeyer** [comment] 2015-09-04 18:39
I think I have solved the issue. Apparently, you have to make sure to normalize the paths when you pass them to the `symlink()` function:

https://github.com/contao/core-bundle/blob/hotfix/4.0.3/src/Command/SymlinksCommand.php#L164-L165)

Now there are no more failing tests on Windows (see https://ci.appveyor.com/project/leofeyer/core-bundle).

**Comment by fritzmg** [comment] 2015-09-04 18:58
Hmm... with this change I am getting at least to the point where you have to set the install tool password. However after that it still says
```
Fatal error: Uncaught exception 'LogicException' with message 'The symlink target "system/themes/flexible" exists and is not a symlink.'
```
This time the symlink is normalized though:
```
 Directory of C:\xampp\htdocs\contao-4.0.2\system\themes

04.09.2015  20:52    <DIR>          .
04.09.2015  20:52    <DIR>          ..
06.08.2015  00:26                57 .gitignore
04.09.2015  20:52    <SYMLINKD>     flexible [C:/xampp/htdocs/contao-4.0.2/vendor/contao/core-bundle/src/Resources/contao/themes/flexible]
               1 File(s)             57 bytes
               3 Dir(s)  27.971.801.088 bytes free
```
This is the path that `validateSymlink` tries to check with `is_link`:
```
C:\xampp\htdocs\contao-4.0.2\system\themes\flexible
```

**Comment by fritzmg** [comment] 2015-09-05 08:06
Just as @jamesdevine I am also unable to get `is_link` to return true for _any_ kind of symlink under windows.

Even if I do something as simple as this:
```php
symlink('C:\\xampp\\htdocs\\test\\test1','C:\\xampp\\htdocs\\test\\linktotest1');

var_dump( is_link('C:\\xampp\\htdocs\\test\\linktotest1') );
var_dump( is_link('C:\\xampp\\htdocs\\test\\linktotest2') );
var_dump( is_link('C:\\xampp\\htdocs\\test\\linktotest3') );
```
(_linktotest2_ and _linktotest3_ are symlinks created with `mklink` in the console beforehand) it returns false for both. This is how the directory looks:
```
 Directory of C:\xampp\htdocs\test

05.09.2015  09:59    <DIR>          .
05.09.2015  09:59    <DIR>          ..
05.09.2015  09:59    <SYMLINKD>     linktotest1 [C:\xampp\htdocs\test\test1]
05.09.2015  09:58    <SYMLINKD>     linktotest2 [C:/xampp/htdocs/test/test2]
05.09.2015  09:58    <SYMLINKD>     linktotest3 [C:\xampp\htdocs\test\test3]
05.09.2015  09:59               218 symlinks.php
05.09.2015  09:57    <DIR>          test1
05.09.2015  09:57    <DIR>          test2
05.09.2015  09:57    <DIR>          test3
              10 File(s)          6.916 bytes
               6 Dir(s)  27.945.472.000 bytes free
```
It seems `is_link` cannot be reliably used at all under Windows, though weirdly it seems to work on some setups.

**Comment by fritzmg** [comment] 2015-09-05 08:12
I'll try testing with a different PHP version. As far as I can see the tests were made with PHP 5.6.3.

**Comment by fritzmg** [comment] 2015-09-05 08:42
Ah, got it now, I forgot about your [earlier comment here](https://github.com/contao/core-bundle/issues/208#issuecomment-137815604):

> http://stackoverflow.com/questions/26600247/how-to-make-windows-symlinks-work-with-mod-php

As far as I have tested, `is_link` does indeed not work at all under Windows (or at least on my setup), when PHP is run as an Apache module. I just switched it to be run via CGI and now the `is_link` test returns true for each of the 3 symlinks. And now the install.php is working as well :)

@jamesdevine try the following to test it yourself: edit `xampp\apache\conf\extra\httpd-xampp.conf` and change these lines
```
#
# PHP-Module setup
#
LoadFile "C:/xampp/php/php5ts.dll"
LoadFile "C:/xampp/php/libpq.dll"
LoadModule php5_module "C:/xampp/php/php5apache2_4.dll"

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>

#
# PHP-CGI setup
#
#<FilesMatch "\.php$">
#    SetHandler application/x-httpd-php-cgi
#</FilesMatch>
#<IfModule actions_module>
#    Action application/x-httpd-php-cgi "/php-cgi/php-cgi.exe"
#</IfModule>
```
to
```
#
# PHP-Module setup
#
#LoadFile "C:/xampp/php/php5ts.dll"
#LoadFile "C:/xampp/php/libpq.dll"
#LoadModule php5_module "C:/xampp/php/php5apache2_4.dll"

#<FilesMatch "\.php$">
#    SetHandler application/x-httpd-php
#</FilesMatch>
#<FilesMatch "\.phps$">
#    SetHandler application/x-httpd-php-source
#</FilesMatch>

#
# PHP-CGI setup
#
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php-cgi
</FilesMatch>
<IfModule actions_module>
    Action application/x-httpd-php-cgi "/php-cgi/php-cgi.exe"
</IfModule>
```
i.e. disable the php module and enable CGI.

By running PHP via CGI, the original SymlinksCommand.php of version 4.0.2 also works.

**Comment by leofeyer** [comment] 2015-09-05 19:16
This issue should have been fixed in PHP 5.3: https://bugs.php.net/bug.php?id=51766 Which PHP version are you using?

See https://github.com/contao-community-alliance/composer-plugin/issues/34 for a possible workaround.

**Comment by fritzmg** [comment] 2015-09-06 06:53
Still the same as in the original post, PHP 5.5.11.

I have also tried using SplFileInfo:
```php
$info1 = new SplFileInfo('C:\\xampp\\htdocs\\test\\linktotest1');
$info2 = new SplFileInfo('C:\\xampp\\htdocs\\test\\linktotest2');
$info3 = new SplFileInfo('C:\\xampp\\htdocs\\test\\linktotest3');

var_dump( $info1->isLink() );
var_dump( $info2->isLink() );
var_dump( $info3->isLink() );
```
but it also returns false in all 3 cases.

**Comment by fritzmg** [comment] 2015-09-06 08:20
> See contao-community-alliance/composer-plugin#34 for a possible workaround.

Something like
```php
function is_symlink($target)
{
	$realpath = realpath($target);

	if ($realpath !== $target) {
		// It is a symlink
		return true;
	}

	// fallback for broken symlinks
	$link = readlink($target);

	if ($link && $link !== $target) {
		// It is a broken symlink
		return true;
	}

	return false;
}
```
will work. However, you have to make sure that all paths are normalized. e.g.:
```php
function is_symlink($target)
{
	$target = strtr($target, '\\', '/');
	$realpath = strtr(realpath($target), '\\', '/');

	if ($realpath !== $target) {
		// it is a symlink
		return true;
	}

	// fallback for broken symlinks
	$link = strtr(readlink($target), '\\', '/');

	if ($link && $link !== $target) {
		// it is a broken symlink
		return true;
	}

	return false;
}
```
Test:
```php
var_dump( is_symlink('C:\\xampp\\htdocs\\test\\linktotest1') );
var_dump( is_symlink('C:\\xampp\\htdocs\\test/linktotest2') );
var_dump( is_symlink('C:/xampp\\htdocs\\test\\linktotest3') );

var_dump( is_symlink('C:/xampp/htdocs/test\test1') );
var_dump( is_symlink('C:\\xampp\\htdocs\\test\\test2') );
var_dump( is_symlink('C:\\xampp\\htdocs\\test\\test3') );
```
Output:
```
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
```

As a side note: is there a benefit from using `strtr` instead of `str_replace`? As far as I read, `strtr` is slower than using `str_replace`.

**Comment by leofeyer** [comment] 2015-09-06 18:17
> On a side note: is there a benefit from using `strtr` instead of `str_replace`? As far as I read, `strtr` is slower than using `str_replace`.

No, it is not. Just run a benchmark test yourself. Even Symfony declined a PR aiming to "fix" this (see [#15410](https://github.com/symfony/symfony/pull/15410)).

**Comment by leofeyer** [comment] 2015-09-06 19:07
This is starting to become a never ending story. Even if we "fix" the `is_link()` check by using `realpath()`, PHP will not be able to create symlinks, because it still treats any existing symlink as file or directory, which `symlink()` is not allowed to overwrite.

@contao/developers Since this seems to be a bug when running XAMPP with mod_php, can we simply make this a "known limitation"? It is possible to [install PHP FastCGI](https://commaster.net/content/installing-php-fastcgi-and-zend-opcache-xampp-windows) on XAMPP, however, it does not come out of the box.

**Comment by Toflar** [comment] 2015-09-07 07:45
Honestly, I read through some PHP bug reports and Pull Requests and they all end up saying that symbolic links cannot be treated the same on *nix and Windows systems. If possible, PHP should handle the different systems, not Contao. So we can do our very best to provide compatibility but I think we've (you have) already done that here. I saw that @fritzmg is following the related PHP core PR's closely so if there's anything we should change, I think he can let us know :)

**Comment by fritzmg** [comment] 2015-09-07 09:55
Yep, though I am still unsure what the deal is with functions like `is_link` and `filetype()` not working when running PHP as an Apache module (and allegedly `symlink()` works in CGI mode better than it does as a module).

For now I am glad that I can run Contao 4 in (Fast)CGI mode under Windows. It's sufficient enough for me at least.

**Comment by leofeyer** [comment] 2015-09-07 10:43
I can confirm that installing PHP as FastCGI on XAMPP fixes the issue, therefore I consider this a PHP or mod_php bug. If it turns out that there is anything we can do about it, I'll happily implement it of course, but for now, I'm going to stop investigating.

**Closed by leofeyer** 2015-09-07 10:43 UTC
Labels: defect

**Comment by DyaGa** [comment] 2015-11-05 10:59
Is it possible just to copy all linked sources on Windows? Like it done for other bundles.

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Trying to install assets as symbolic links.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
It looks like your system doesn't support symbolic links, so the assets were installed by copying them.
Installing assets for Contao\CalendarBundle into web/bundles/contaocalendar
It looks like your system doesn't support symbolic links, so the assets were installed by copying them.
```

**Comment by fritzmg** [comment] 2015-11-19 09:06
@DyaGa that's probably not feasible, since Contao also uses symlinks from `/web/files` to `/files` to make your files publicly accessible (on demand).

**Comment by fritzmg** [comment] 2015-12-14 08:22
Unfortunately, the `symlink()` function is still broken for relative symlinks under Windows in PHP 7: https://github.com/php/php-src/pull/1243#issuecomment-164195109

**Comment by Zeromax** [comment] 2016-03-16 20:45
Just as a hint: https://github.com/symfony/symfony-standard/issues/480#issuecomment-12524995
You have to run the CMD or PS with Admin Priviledge. Then everything works fine and the symlinks are created.

![unbenannt](https://cloud.githubusercontent.com/assets/1867177/13827974/86082758-ebbf-11e5-9883-c90b072c4ff7.PNG)

**Comment by fritzmg** [comment] 2016-03-27 10:11
> Ok, so this did not work so well: contao/core#7847

imho the real question here is: why do the files in `$folders` have a leading slash (regardless of whether it's a forward or backslash? In any other place in Contao the part of a path that is relative to `TL_ROOT` does not have a leading slash. I haven't looked at the code of DC_Folder yet.
