### ISSUE TITLE
Enhancement: Use new dcapicker for include article CE

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#833] opened 2017-05-18 18:53 UTC
Instead of using the current select field to choose an article for insertion, the new dca picker could also be used for article selection.
Using the select field for multi page setups can be quite messy if you have articles with the same names across some of the page trees.

Maybe the dca picker could even be extended to also ship with a content element selection for the corresponding include element.

**Comment by asaage** [comment] 2017-05-19 01:34
duplicate of https://github.com/contao/core-bundle/issues/747

**Comment by leofeyer** [comment] 2017-05-19 07:01
This is not a duplicate of #747.

**Comment by agoat** [comment] 2017-07-03 12:21
see #912

**Closed** 2017-07-03 13:10 UTC
Labels: feature
