### ISSUE TITLE
composer install or update throws error

### ISSUE THREAD

**Issue by tsarma** [contao/core-bundle#858] opened 2017-05-30 09:38 UTC
Contao 4.3.10

```
> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Contao\CoreBundle\Composer\ScriptHandler::generateRandomSecret
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand' not found in /var/www/_Contao4/contao43100/vendor/contao/core-bundle/src/Command/DoctrineMigrationsDiffCommand.php on line 27
PHP Stack trace:
PHP   1. {main}() /var/www/_Contao4/contao43100/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->__construct() /var/www/_Contao4/contao43100/bin/console:32
PHP   3. Symfony\Component\Console\Application->__construct() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:43
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->add() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:90
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:124
PHP   6. Symfony\Component\HttpKernel\Bundle\Bundle->registerCommands() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:143
PHP   7. ReflectionClass->__construct() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Bundle/Bundle.php:192
PHP   8. spl_autoload_call() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Bundle/Bundle.php:192
PHP   9. Symfony\Component\Debug\DebugClassLoader->loadClass() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Bundle/Bundle.php:0
PHP  10. require_once() /var/www/_Contao4/contao43100/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:144
```

**Comment by fritzmg** [comment] 2017-05-30 12:33
Duplicate of #760

**Closed** 2017-05-30 19:51 UTC
