### ISSUE TITLE
PrettyErrorScreen does not support errors

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#1530] opened 2018-05-23 07:42 UTC
https://github.com/contao/core-bundle/blob/master/src/EventListener/PrettyErrorScreenListener.php#L249

I guess this should be `\Throwable`. Not sure how to fix this in 4.4 where we support PHP < 7, but probably just by not having an argument at all?

**Comment by Toflar** [comment] 2018-05-23 08:12
https://github.com/symfony/polyfill/tree/master/src/Php70#compatibility-notes :)

**Comment by leofeyer** [comment] 2018-06-11 08:22
It seems that the polyfill only adds the `Error` class but not the `Throwable` interface?

**Comment by leofeyer** [comment] 2018-06-15 10:11
There are more places where `\Exception` is used either as type hint or in a `catch` clause. What about those occurrences?

**Comment by aschempp** [comment] 2018-06-15 11:34
More places in the listener or in the application?

**Comment by leofeyer** [comment] 2018-06-15 12:18
Both.

**Comment by leofeyer** [comment] 2018-06-15 14:27
I actually was not able to reproduce this. I have added `throw new \DivisionByZeroError();` in the `FrontendIndex` class and the pretty error screen was displayed properly.

How do I reproduce this?

**Comment by aschempp** [comment] 2018-06-19 06:51
I'm pretty sure it was just an _invalid index_ error for me…

**Comment by leofeyer** [comment] 2018-09-06 18:36
This has been fixed in contao/contao#32.

**Closed by leofeyer** 2018-09-06 18:36 UTC
Labels: defect, unconfirmed
