### ISSUE TITLE
4.4.8: The {{form::FIELD}} insert tag will be replaced forever after a form submit

### ISSUE THREAD

**Issue by benfolds** [contao/core-bundle#1230] opened 2017-12-12 16:33 UTC
When using the {{form::FIELD}} insert tag, it will not only be replaced at the following page but on every page after submitting the form. This behaviour is weird when using the insert tag as trigger for a successful submit.

**Comment by leofeyer** [comment] 2017-12-15 16:25
This is because Contao stores the form data in the session so you can create multi-page forms. It can probably be fixed with an insert tag flag?

@contao/developers /cc

**Comment by ausi** [comment] 2017-12-16 12:37
How would the flag determine if it is the first pageview after the form was submitted?

**Comment by leofeyer** [comment] 2017-12-16 16:52
It cannot I guess.

**Comment by asaage** [comment] 2017-12-20 13:38
@benfolds did you mean the `{{post::FIELD}}` insert tag?
`{{form::FIELD}}` looks to me like it's related to efg - i could not find any documenation about that in the code/docs.
For the `{{post::FIELD}}` i would also like to have it replaced only if it was a post-request.

**Comment by fritzmg** [comment] 2017-12-20 13:40
> For the {{post::FIELD}} i would also like to have it replaced only if it was a post-request.

Then you would not be able to easily show certain info on the success page of a form anymore.

**Comment by asaage** [comment] 2017-12-20 13:43
i see..
i was assuming you get to a success-page via post.

**Comment by fritzmg** [comment] 2017-12-20 13:45
No, the form is processed on the same page and then you are redirected to the success page.

**Comment by benfolds** [comment] 2017-12-21 10:13
@asaage You are right, it is {{post::FIELD}}
Sorry for the mess...

**Comment by leofeyer** [comment] 2018-03-15 15:40
As discussed in Mumble on March 15th, this is the expected behavior of Contao so you can create multi-page forms. Can you elaborate on your use case? Maybe there is another way of solving it.

**Closed** 2018-08-21 16:15 UTC
Labels: defect, feedback required

**Comment by padarom** [comment] 2018-09-14 09:40
An example use case for this is forms that don't have a redirect. Having a "success" page with just a "Thank you for submitting this form" is not always viable or desired. Instead you might want to show the success message before the form (or at least on the same page).

So far we have done it with a hidden field that contained the success message that's supposed to be shown when the form was submitted. The issue is that form data is forcibly persisted, so this message will always be shown after submitting a form, even after another page reload.

A possible solution could be to use an insert tag flag that resets a session variable once rendered: `{{post::field|onlyonce}}`. I'm not sure about the internals, but let's say this outputs the value of `$_SESSION['FORM_DATA']['field']`. Then once the insert tag is rendered, the `'field'` key is unset, so on any further requests to the same page it won't be displayed anymore.

This doesn't seem to break anything regarding multi-page-forms as far as I can see.

**Comment by aschempp** [comment] 2018-09-17 06:07
This should no longer be the case with Contao 4.6, as the implementation has been optimized (to reduce session usage).
