### ISSUE TITLE
Adding an image in the text editor ends in page not found

### ISSUE THREAD

**Issue by christophKi** [contao/core-bundle#1419] opened 2018-03-09 19:47 UTC
Worked with Contao 4.4.14
Broken on 4.4.15 & 16

Tested on Debian & Centos. 

![image](https://user-images.githubusercontent.com/29779413/37226522-805cd57e-23da-11e8-9d03-8062a5ff212d.png)

![image](https://user-images.githubusercontent.com/29779413/37226570-a904b7da-23da-11e8-9380-b4c9635b2c5b.png)

**Comment by xchs** [comment] 2018-03-09 19:52
Duplicate of https://github.com/contao/core-bundle/issues/1415

**Closed** 2018-03-09 20:02 UTC
Labels: duplicate
