### ISSUE TITLE
wrong 404 page shown for URLs that have no suffix

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1172] opened 2017-11-04 11:27 UTC
Tested with Contao 4.4.7.

__Reproduction:__

1. Set the primary and secondary language of your browser to _English_.
2. Leave the `contao.url_suffix` at its default value (`.html`).
3. Set `prepend_locale: true`, clear the cache.
4. Create a website root for language `en`.
5. Create a 404 page with English text within that website root.
6. Create a website root for language `de`.
7. Create a 404 page with German text within that website root.
8. Test the following URLs:

* http://example.org/de/foo.html
* http://example.org/de/foo

The first URL will show the German 404 page as expected.

The second URL will show the English 404 page, even though the URL clearly has the `/de` language fragment in it. 

As indicated with the first reproduction step, the language shown for such a URL depends on the `Accept-Language` of the request header actually. So if your browser is set to _German_, you can test with the following URLs instead:

* http://example.org/en/foo.html
* http://example.org/en/foo

The first URL will show the English 404 page, the second one will show the German 404 page.

**Comment by leofeyer** [comment] 2017-11-07 20:22
@contao/developers Do you think we should handle this case? URLs without the URL suffix are not valid Contao URLs and therefore Contao should not try to extract anything from them IMO.

**Comment by ausi** [comment] 2017-11-08 08:45
If it’s an easy fix, I think we should do it.

**Comment by Toflar** [comment] 2017-11-08 09:11
> URLs without the URL suffix are not valid Contao URLs and therefore Contao should not try to extract anything from them IMO.

I agree, it's not a Contao URL so why does it redirect to the English 404 page then? :D

**Comment by fritzmg** [comment] 2017-11-08 09:13
It does not redirect, it simply generated the 404 page of the primary `Accept-Language` (or fallback).

**Comment by fritzmg** [comment] 2017-11-08 09:13
> What if I configured an empty URL suffix?

Then such URLs would show the regular 404 page and URLs with an URL suffix possibly will not.

**Comment by bytehead** [comment] 2017-11-08 09:17
Contao should only handle this kind of cases, when a route with a `contao_` prefix matches.

**Comment by fritzmg** [comment] 2017-11-08 09:20
> Contao should only handle this kind of cases, when a route with a contao_ prefix matches.

Which is true for any URL ;) [routing.yml#L25-L33](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/config/routing.yml#L25-L33)
```yml
# The catch all route must be the last one!
contao_catch_all:
    path: /{_url_fragment}
    defaults:
        _scope: frontend
        _token_check: true
        _controller: "ContaoCoreBundle:Frontend:index"
    requirements:
        _url_fragment: .*
```

**Comment by bytehead** [comment] 2017-11-08 09:24
contao_catch_all should be the very last rule of the routing config.

**Comment by fritzmg** [comment] 2017-11-08 10:07
Yes of course, but that's not the point. Any URL is a valid Contao URL currently.

**Comment by bytehead** [comment] 2017-11-08 10:42
> Any URL is a valid Contao URL currently. 

Thats a problem, if somebody has a Symfony application and adds the `contao\core-bundle` later.
Contao should only care about Contao URLs and not about others.

**Comment by fritzmg** [comment] 2017-11-08 11:12
Yes, but Contao URLs are currently only processed via the `contao_root` and `contao_catch_all` route.

If you use the `core-bundle` in your Symfony app, you need to make sure yourself, that its routes are the last ones loaded.

**Comment by Toflar** [comment] 2018-01-29 12:20
This is indeed an issue, we have to do something about it. It was completely confusing for me and I debugged quite a bit and didn't even remember that issue here :) So either the issue is that it does not find the correct 404 page to render or the issue is that it tries to render one even though it should not be considered a Contao request.
We can handle this case properly once we switch to proper router handling but until then, we have to make a decision here.

**Comment by leofeyer** [comment] 2018-02-15 15:53
As discussed in Mumble on February 15th, a first step to solving the problem would be to move this block

https://github.com/contao/core-bundle/blob/483e7fe6da764f152935308bb8117f5d602290df/src/Resources/contao/classes/Frontend.php#L99-L121

before this block

https://github.com/contao/core-bundle/blob/483e7fe6da764f152935308bb8117f5d602290df/src/Resources/contao/classes/Frontend.php#L82-L97

**Comment by leofeyer** [comment] 2018-02-20 21:36
Fixed in fae22c6fe14e0eaa9440a384d72d1c08f961c251.

**Comment by fritzmg** [comment] 2018-04-24 10:05
This still happens in Contao 4.4.18.

**Comment by fritzmg** [comment] 2018-10-25 11:21
Still happening in Contao 4.4.26 & 4.6.6

**Comment by leofeyer** [comment] 2018-10-30 14:21
Apparently, the change from fae22c6fe14e0eaa9440a384d72d1c08f961c251 is no longer there. It is actually not in the history, either. 🤔 

Re-added in contao/contao@65b5d5534fa0476d6ea27f5525a4467fabae18f5.

**Closed by leofeyer** 2018-10-30 14:21 UTC
Labels: defect
