### ISSUE TITLE
[4.3. Bug] Generate aliases for pages with russian names is broken

### ISSUE THREAD

**Issue by DyaGa** [contao/core-bundle#848] opened 2017-05-25 13:13 UTC
Hi.

It doesn't generate at all for russian words.

For example: 

- create any page in Site structure with names like `Первая страница`, `Вторая страница`;
- generate aliases for them;
- the result will be an empty alias value, but excepted to see `Pervaja-stranica` (or something like this).

**Comment by aschempp** [comment] 2017-05-25 14:51
Did that work in a previous version?

**Comment by fritzmg** [comment] 2017-05-25 17:00
It should work in Contao 3, yes: https://github.com/contao/core/blob/master/system/helper/utf8_lookup.php#L189-L196

Probably duplicate of #560. The PR is still WIP: #569

**Comment by leofeyer** [comment] 2017-05-29 13:55
It is true that transliteration is broken in Contao 4 (since switching to `patchwork/utf8` to be exact). And it can only be solved by #569, which we forgot to merge. But there are two solutions IMO:

1. Do not transliterate at all.

We have already dropped transliteration for file and folder names in Contao 4.4.0-beta1, so why not just drop it for aliases, too? Any browser should be able to handle URLs like `https://localhost/app_dev.php/ru/первая-страница.html`.

2. Use the Slugify service to transliterate.

The service might not handle all languages, otherwise its fine.

@contao/developers /cc

**Comment by leofeyer** [comment] 2017-05-29 14:13
I have removed the broken transliteration in 1dbbf9f6f281fdaf3a8e65c95b583c3ac74d96bb. We might add Slugify in Contao 4.5, because it implies further changes (such as moving the `forlderUrls` setting from the `localconfig.php` file to the `config.yml` file) that I don't want to add this short before the final release.

**Closed by leofeyer** 2017-05-29 14:13 UTC
Labels: defect

**Comment by Toflar** [comment] 2017-05-29 14:17
To be honest, I think it depends. It's something that should be a setting of a root page. If you think in German, somebody might want to have URI's like `foobar.de/über-uns.html` and an other one would like to have `foobar.de/ueber-uns.html`. It's a matter of taste. Also I think `prepend_locale` as well as `folderUrls` are both settings that should be a root page setting, not a system setting. There are other tickets where people would like to have the main language to be accessible via `www.domain.de` and all translations via `www.domain.de/{locale}`. If it was configurable in the root page settings, I guess this would be possible too then. So I think we should mark that as a feature for 4.5.

**Comment by leofeyer** [comment] 2017-05-29 14:19
You should copy your comment to https://github.com/contao/core-bundle/pull/569. This is just the bug report for the broken transliteration caused by `Utf8::toAscii()`.

**Comment by tsarma** [comment] 2019-02-15 16:10
Please make ```$arrSearch``` and ```$arrReplace``` customizable somewhere in global array. Striping away special characters in ```Tibetan``` language lose the meaning of the word.
