### ISSUE TITLE
language in URL but not in "main" page tree

### ISSUE THREAD

**Issue by heimseiten** [contao/core-bundle#1051] opened 2017-09-02 08:40 UTC
Is it possible to add a parameter in the parameters.yml, so that the language in the URL is not in, for instance, the first page tree. Or not in the fallback language page tree. To avoid a redundant URL like: domain.de/de/

**parameters.yml example**
parameters:
    prepend_locale: true
    prepend_locale_for_first_page_tree: false
or
    prepend_locale_not_in_fallback_language_page_tree: true

**So that the result looks like this:**
domain.de
domain.de/en/
apple.com
apple.com/de/

I think this should be good for SEO as well as for the aesthetic of the domain.

**Comment by fritzmg** [comment] 2017-09-02 10:56
There would be no advantage for SEO as far as I can tell.

**Comment by asaage** [comment] 2017-09-02 12:50
That would be a nice feature.
https://github.com/contao/core/issues/8498#issuecomment-248707838

**Comment by Aybee** [comment] 2017-09-02 17:48
Mmh, not necessary I think. The TLD stands not for a language. In Contao the /de|en/ stands for languages. Just a note to this feature request.

**Comment by ausi** [comment] 2017-09-12 13:56
This feature has a major downside: The language detection of the users language cannot work anymore. This is also true for apple.com, it always shows the english version of the website even if you browse with German language settings.

**Comment by heimseiten** [comment] 2017-09-12 15:20
That is a downside indeed.

But since most visitors come via search engines, I think the feature would be nice anyway. Even if language detection does not work anymore. Simply to avoid a domain like domain.de/de/ as "main" domain.

**Comment by ausi** [comment] 2017-09-13 16:23
> Simply to avoid a domain like domain.de/de/ as "main" domain.

You can also use one domain per language, e.g. domain.de, domain.fr, domain.com.

**Comment by agoat** [comment] 2017-09-19 15:44
> This feature has a major downside: The language detection of the users language cannot work anymore. 

Just a quick idea: What if we set a cookie and only detect and redirect on the very first call?

**Comment by Toflar** [comment] 2017-09-19 16:47
I think that's not a good idea. Cookies essentially force every client request to be treated as a private request. It's like if you started a PHP session (which is nothing else than a cookie but I noticed it helps people understanding 😄 ). The reverse proxy now always has to do complicated work to find out if it can actually serve you a copy from the cache or if it has to ask the application for your individual (based on the cookie) response.

We can spend more time evaluating but I think it'll never be worth the effort.

**Comment by asaage** [comment] 2017-09-20 00:11
> There would be no advantage for SEO as far as I can tell.

I think it would skip 1 301redirect for the main-target-audience in case you use a countrycode-tld.

>downside: The language detection of the users language cannot work anymore. 

are you shure? I think with rewriterules in a serverconfiguration (htaccess) this could easily be achived (strip **/de** if **tld=de**) why shouldn't it be possible to strip **/lang_code** if **browser-language-setting=contao:domain-language-fallback-setting**?

personal preference: I'd rather do without language-detection than having urls like *'domain.de/de/' or 'domain.fr/fr'* since searchengines most-likely would send you to the appropriate location anyway but
 [changelanguage](https://github.com/terminal42/contao-changelanguage) would more or less be required then and it's not part of the core.

>one domain per language, e.g. domain.de, domain.fr, domain.com.

could be costly and in some cases impossible
using subdomains e.g. domain.de, fr.domain.de, en.domain.de can be an option if  [changelanguage](https://github.com/terminal42/contao-changelanguage) is installed but does not look nice either.

**Comment by patrickjDE** [comment] 2017-09-20 02:36
> I think it would skip 1 301redirect for the main-target-audience in case you use a countrycode-tld.
Which should be the only redirect that is happening. And that is perfectly fine for SEO.

**Comment by agoat** [comment] 2017-09-20 07:40
> why shouldn't it be possible to strip /lang_code if browser-language-setting=contao:domain-language-fallback-setting?

The problem is that if a visitor call '_domain.de_' and 'english' is the preferred browser languages we could redirect him to '_domain.de/en_'. But what if he want to read the german root page (language switch de/en). He would never be able to call '_domain.de_' because everytime he will redirected to his prefered language. [changelanguage](https://github.com/terminal42/contao-changelanguage) wouldnt be able to work properly in this scenario.

**Comment by agoat** [comment] 2017-09-20 07:54
> Cookies essentially force every client request to be treated as a private request.

But is a PHP session not started all the time? When I call contao.org I have the following cookies saved automatically:

Name | Domain | Value
--- | --- | ---
_cfuid | .contao.org | d50847c87c7578dcc4fbaffe773e0f84a1485537923
_gat | contao.org | 1
_ga | contao.org | GA1.1.1368365212.1486461613
PHPSESSID | contao.org | p89u5gunej9k85rlogjldumkjd

Looks like a PHP session is started.

> The reverse proxy now always has to do complicated work to find out if it can actually serve you a copy from the cache or if it has to ask the application for your individual 

I'm still a beginner in Symfony and I don't really understand how the reverse proxy works.
But is it not possible to set a simple cookie, which is evaluated only for language redirection?

How are normal page redirects handled in the reverse proxy. What if the redirect is happening on condition. Might this a problem for the reverse proxy?

**Comment by ausi** [comment] 2017-09-20 09:58
> Just a quick idea: What if we set a cookie and only detect and redirect on the very first call?

Not a good idea IMO. If a search engine tries to index the website (without cookies) it can never reach the home page for the main language of the website, if the preferred language of the search engine is not equal to the main language of the website.

**Comment by agoat** [comment] 2017-09-20 10:41
> Not a good idea IMO. If a search engine tries to index the website (without cookies) it can never reach the home page for the main language of the website, if the preferred language of the search engine is not equal to the main language of the website.

What if we save it in the session data? But that's maybe more a problem for the 'Symfony reverse proxy' as @Toflar wrote above.

> This is also true for apple.com, it always shows the english version of the website even if you browse with German language settings.

Apple don't do any automatic language detection. Simply redirect apple.de to apple.com/de.
Microsoft has automatic language detection, but it look's like they use some kind of geo-ip solution.
Just to have an example of twp big companies.

Anyway, to have the visitor redirected to his preferred language is a big benefit in usability. We just have the problem with the very first hit on the root page. Not sure if we could find a solution without drawbacks.

**Comment by ausi** [comment] 2017-09-20 11:50
> Microsoft has automatic language detection,

And the english version is at *microsoft.com/en-us/* not at *microsoft.com/*

**Comment by asaage** [comment] 2017-09-20 12:12
Just tested: microsoft.com does not care about your browser-language :no_mouth:
They use your ip or proxy-ip to figure out where to send you first.

**Comment by agoat** [comment] 2017-09-20 12:21
> Just tested: microsoft.com does not care about your browser-language 😶
They use your ip or proxy-ip to figure out where to send you first.

But once you selected a language, they set a cookie `mslocale=>{'u':'de-de'}` and you will be redirected to _microsoft.com/de-de_ when just opening _microsoft.com/_

But you have to select the language actively. Just opening the '/de-de' page doen't change the cookie.

**Comment by agoat** [comment] 2017-09-20 12:33
> If a search engine tries to index the website (without cookies) it can never reach the home page for the main language of the website, if the preferred language of the search engine is not equal to the main language of the website.

At least the google bot don't send a `Accept-Language` header (see [here](https://support.google.com/webmasters/answer/6144055?hl=en&ref_topic=2370587)). So the default language page is received and there is no redirection.

**Comment by ausi** [comment] 2017-09-20 12:56
> At least the google bot don't send a `Accept-Language` header (see [here](https://support.google.com/webmasters/answer/6144055?hl=en&ref_topic=2370587)). So the default language page is received and there is no redirection.

This is not true. Did you read the whole article behind your link?

> In addition, the crawler sends HTTP requests without setting `Accept-Language` in the request header.  
> ...  
> **Language-dependent crawling:** Googlebot crawls with an Accept-Language field set in the HTTP header.

**Comment by fritzmg** [comment] 2017-09-20 13:02
> But once you selected a language, they set a cookie mslocale=>{'u':'de-de'} and you will be redirected to microsoft.com/de-de when just opening microsoft.com/

But that does not matter - microsoft.com does not do what you want anyway ;).

**Comment by agoat** [comment] 2017-09-20 13:20
> This is not true. Did you read the whole article behind your link?

Ok. That was misleading. The google bot may additionally do a request without sending a 'Accept-Language' header.

Anyway, I see the drawbacks with a cookie or session solution in our case.

**Comment by asaage** [comment] 2017-09-21 10:58
I get the point: auto-language-detection works only with consistent prepend locale or different domain...
But please correct me if im wrong!
If you do **not** ```prepend_locale``` but activate **folder-urls** and prepend the lang-code to your sites manually it will work. right?

**Comment by agoat** [comment] 2017-09-21 11:26
> If you do not prepend_locale but activate folder-urls and prepend the lang-code to your sites manually it will work. right?

Yes and No. If you have e.g. a german und english root page and one have 'index' as the alias for the first page, the page will not be able to be viewed if the preferred browser language do not match.

To have an example let's assumed we have:
- domain.de (type: root, language: de , fallback: yes) 
-- Erste Seite (type: regular page, alias: index)

- domain.de (type: root, language: en)
-- First page (type: regular page, alias: en)


#### Case 1
A visitor with 'de' as preferred language will see 'Erste Seite' from the 'de' root page.
#### Case 2
A visitor with 'en' as preferred language will redirected to 'domain.de/en' and will see 'First page'.
#### Case 3
But if the visitor with 'en' want to see the german root page (by clicking on a language switch menu), contao again try to find the matching root for the preferred language and the visitor will be redirected to 'domain.de/en'. 

If the root page is requested under 'domain.de', contao try to find the root page matching the preferred language. Unless the language redirection would be disabled, visitors will always be redirected to the root oage matching the preferred language (or if nothing matches the fallback root).

To add a condition, and look if it's the first hit from the visitor, would theoretically be possible, but has some (fundamental) drawbacks described above.

**Comment by asaage** [comment] 2017-09-21 11:46
I'm going to live with what i've got an try to avoid country-tld's for multilingual sites in the future then.
:disappointed:

**Comment by leofeyer** [comment] 2017-10-05 15:00
As discussed in Mumble on October 5th, we want to add this feature. However, it implies quite some work such as moving the `contao.prepend_locale`, `doNotRedirectEmpty` and `folderUrl` settings to the root pages in the site structure.

**Comment by Messa1** [comment] 2019-04-08 14:01
And what was the result of the discussion? I'm currently looking for a solution to set prepend_locale for different domains? (Website starting points)

**Comment by asaage** [comment] 2019-04-08 18:46
```folderUrl``` and ```doNotRedirectEmpty``` settings -> https://github.com/contao/contao/issues/203
```prepend_locale``` -> revisiting this issue i honestly do not see it happening without sacrificing automatic redirection after languagedetection.

**Comment by fritzmg** [comment] 2019-04-08 22:25
@Messa1 there is no solution (within the core) yet. You'll have to wait and see if the next feature releases will add it.

**Comment by agoat** [comment] 2019-04-09 05:33
Have a look at the [permalink extension](https://packagist.org/packages/agoat/contao-permalink). 

This allows you to set up a separate URL scheme for each domain (with/without locale in the URL).

**Comment by leofeyer** [comment] 2020-06-11 16:04
This will be possible as soon as https://github.com/contao/contao/pull/1516 has been merged (expected in Contao 4.10).

**Closed by leofeyer** 2020-06-11 16:04 UTC
Labels: feature
