### ISSUE TITLE
contao/core-bundle replaces contao/core

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#278] opened 2015-05-18 14:07 UTC
We should update the composer file.

https://github.com/contao/core-bundle/blob/develop/composer.json#L57

The current "conflict" does not allow to install any existing Contao extension, because they require `contao/core`. That could imho be solved be using `replace`.

**Comment by leofeyer** [comment] 2015-05-18 15:12
I recall that `replace` did not work for another reason. But I'm sure @discordier can shed some light on this :)

**Comment by discordier** [comment] 2015-05-18 17:09
Have a look at the previous discussion at #150 and #146.

There most definately will be problems with the integration and AFAIR we agreed that ppl. must release new versions of their extensions for Contao 4.0 anyway (following semver) as the change of the dependency is by design non bc.

**Comment by discordier** [comment] 2015-05-18 17:10
It's a pity that we lost the change set and line links almost entirely due to the importing.

**Comment by aschempp** [comment] 2015-05-18 17:15
> ppl. must release new versions of their extensions for Contao 4.0

Well that is certainly true, but as Contao 4 is compatible with most extensions, the extensions should be able to be compatible with Conato 3 and Contao 4. As an example, I've updated [easy_themes](https://github.com/terminal42/contao-easy_themes/commits/hotfix/2.1.3) today and the version is now fully compatible with both versions. But obviously composer can't handle that right now.

**Comment by leofeyer** [comment] 2015-05-18 17:40
> the extensions should be able to be compatible with Conato 3 and Contao 4

I second this.

**Comment by leofeyer** [comment] 2015-05-18 17:41
Still the conflict is correct. You cannot install both `contao/core` and `contao/core-bundle`. Actually, we would have to tell composer that we require either the one or the other. Don't know if that's possible though.

**Comment by aschempp** [comment] 2015-05-18 17:43
That's exactly what "replace" does. If you installed `contao/core-bundle`, it will never ask to install `contao/core`.

**Comment by leofeyer** [comment] 2015-05-18 17:45
Correct. Except for #150 and #146 :)

**Comment by ausi** [comment] 2015-05-19 07:42
> the extensions should be able to be compatible with Conato 3 and Contao 4

This is very important IMHO.

Isn’t it possible to use both, `replace` and `conflict` if we specify the correct version constraints?

```json
"replace": {
	"contao/core": "self.version"
},
"conflict": {
	"contao/core": "<4.0"
},
```

IMO all Contao 4 bundles should conflict with `contao/core <4.0`.

As an extension developer i can then use `"contao/core": ">=3,<5"` to be compatible with Contao 3 and 4.

**Comment by discordier** [comment] 2015-05-19 11:01
The main problem is, that you are telling by replace that the package is "good enough" as the other which is simply not true as all modules have been extracted into own bundles. The only correct candidate would therefore be contao/contao but that also does not work for above reasons.

**Comment by aschempp** [comment] 2015-05-19 11:12
That's somewhat true, as it would not be possible to require `contao/news-bundle` in the composer.json and still be compatible with Contao 3.

How about using a "provides" in `contao/core` that would provide `contao/core-bundle`, `contao/news-bundle` etc? That's also something which would not affect any version of Contao but just something @discordier has to adjust in his package.

**Comment by ausi** [comment] 2015-05-19 11:21
> The main problem is, that you are telling by replace that the package is "good enough" as the other which is simply not true as all modules have been extracted into own bundles.

But we would only replace `self.version` so IMO it should be OK to break BC because it’s a new major version and `contao/core 4.0` no longer includes the extracted modules.

**Comment by aschempp** [comment] 2015-05-19 11:25
@ausi it would not be possible to require the news module for extensions that support both Contao 3 and Contao 4.

**Comment by ausi** [comment] 2015-05-19 11:32
@aschempp it could be done as you said: `contao/core 3.5` “provides” `contao/news-bundle 3.5` and `contao/core 4` doesn’t provide it.

**Comment by aschempp** [comment] 2015-05-19 11:45
there is no `contao/core 4` ;-)

```js
"contao/core": {
    "provides": {
        "contao/core-bundle": self.version,
        "contao/news-bundle": self.version,
        "contao/calendar-bundle": self.version,
        "contao/newsletter-bundle": self.version,
        "contao/listing-bundle": self.version
        /* ... */
    }
}
```

In my extension compatible with both Contao 3 and Contao 4, I would then set `require: { contao/core-bundle: >3.2,<5 }`. It probably means that the Contao 3 composer plugin needs to be adjusted though, as it would not detect the necessary Contao version.

**Comment by leofeyer** [comment] 2015-05-19 12:06
Can't both `contao/core-bundle` and `contao/contao` replace `contao/core`? Or can't `contao/contao` replace `contao/core-bundle` (and the other bundles)?

**Comment by aschempp** [comment] 2015-05-19 12:17
The problem is that you cannot add a dependency on the news module that way.

**Comment by leofeyer** [comment] 2015-05-21 07:00
As discussed on Mumble, the problem needs to be solved in the [composer-plugin](https://github.com/contao-community-alliance/composer-plugin). I'm therefore closing the ticket in favor of contao-community-alliance/composer-plugin#41.

**Closed by leofeyer** 2015-05-21 07:00 UTC
Labels: defect, up for discussion
