### ISSUE TITLE
HTTPS setting in site structure is ignored

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#592] opened 2016-10-14 16:43 UTC
1. log into the backend via `http`
2. edit the settings of any website root
3. __enable__ _DNS settings_ » __Use HTTPS__
4. enable _XML Sitemap_ » __Create an XML sitemap__, set a name and then save
5. go to _System_ » _Maintenance_, activate __Recreate the XML files__ and click _Purge data_

View the created XML file unter `/web/share`. The URLs will still be `http` instead of `https`. Also if you do _Rebuild index_, the URLs will also use `http` instead of `https`.

1. log into the backend via `https`
2. edit the settings of any website root
3. __disable__ _DNS settings_ » __Use HTTPS__
4. enable _XML Sitemap_ » __Create an XML sitemap__, set a name and then save
5. go to _System_ » _Maintenance_, activate __Recreate the XML files__ and click _Purge data_

View the created XML file unter `/web/share`. The URLs will still be `https` instead of `http`. Also if you do _Rebuild index_, the URLs will also use `https` instead of `http`.

1. log into the backend
2. edit the settings of any website root
3. __enable__ _DNS settings_ » __Use HTTPS__
4. enable _XML Sitemap_ » __Create an XML sitemap__, set a name and then save
5. execute `php app/console contao:automator generateXmlFiles` on the console

View the created XML file unter `/web/share`. The URLs will be `http` instead of `https`.

**Comment by xchs** [comment] 2016-10-15 00:22
I cannot reproduce on my system. Do you run the website and the back end over HTTPS, actually?

**Comment by fritzmg** [comment] 2016-10-15 06:47
That shouldn't matter  should it? If you want your sitemaps to use https, they should use https.

**Comment by fritzmg** [comment] 2016-10-15 07:48
I have updated the issue accordingly. The HTTPS setting of the site structure is ignored completely.

**Comment by leofeyer** [comment] 2016-10-16 18:51
> That shouldn't matter, should it?

It does matter before Contao 4.1.2 (see [change log](https://github.com/contao/core-bundle/releases/tag/4.1.2)).

**Comment by fritzmg** [comment] 2016-10-16 18:54
? I don't understand, is the _Use HTTPS_ option not used anymore? If that's deliberate, why does it still exist?

**Comment by leofeyer** [comment] 2016-10-16 19:10
I don't know what you mean. The option is called "Use HTTPS in sitemaps" in Contao < 4.1.2 and does only affect sitemaps there. We have renamed the option to "Use HTTPS" in Contao 4.1.2 and are now considering it everywhere.

Just like @xchs, I cannot reproduce your initial problem. The sitemap URLs have `http://` if "Use SSL" is not checked and `https://` if it is checked.

**Comment by fritzmg** [comment] 2016-10-16 20:13
Hm, for me and at least one other forum user it does not work. https is only used, if you are currently logged in to the back end via https. If you are logged in into the back end via http __or__ if you use the command line to recreate the site map for example, http is used, regardless of the  _Use HTTPS_ setting. 

I'll try to debug it myself. May be it's a platform issue.

**Comment by xchs** [comment] 2016-10-16 20:23
> could you also confirm that the new reproduction steps do not yield any such problems?

I'll try and get back to you later.

**Comment by xchs** [comment] 2016-10-16 22:58
I can confirm all three cases from the issue description above.

Basically, the generated URLs from the XML sitemap only depend on whether the back end is running over HTTP or HTTPS, respectively. It actually doesn't matter how the _"Use HTTPS"_ option is set.

By executing the console command `php app/console contao:automator generateXmlFiles` I always get `http://localhost[/…]` URLs in the generated XML sitemap.

**Comment by leofeyer** [comment] 2016-10-17 06:46
I can reproduce the issue on the command line (still not in the browser).

**Comment by fritzmg** [comment] 2016-10-17 06:47
Did you log into back end via `http`?

**Comment by leofeyer** [comment] 2016-10-17 09:24
Fixed in 27b9b98537ed782e7659b8bbaac6e94b01ce8e38. Will back port the fix to Contao 4.2.5.

**Closed by leofeyer** 2016-10-17 09:24 UTC
Labels: defect

**Comment by discordier** [comment] 2016-10-17 16:27
Technically this is not a backport, backporting would be fixing in 4.X and porting back to 3.X :smiling_imp:

**Comment by leofeyer** [comment] 2016-10-17 18:06
It has been added to the version 4.3.x branch, so if I want to have it in the 4.2.x branch as well, I need to back port it, don't I?

**Comment by leofeyer** [comment] 2016-10-20 10:07
Back ported in f94de5a3e6c74a41395e1b9d46f2ddea9aae6db2.
