### ISSUE TITLE
The search index can't rebuild in multidomain installation

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#633] opened 2016-11-24 10:57 UTC
When trying to rebuild the search index in the backend, all other domains, than the one logged in, can´t be indexed. The reason is `Access-Control-Allow-Origin`.

From the chrome dev tools log:
```
XMLHttpRequest cannot load https://test.agoat.info/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://contao4.agoat.info' is therefore not allowed access.
```

Can the Access-Control-Allow-Origin Header be added safely?

**Comment by fritzmg** [comment] 2016-11-26 13:38
See [fritzmg/contao-multidomain-rebuild-index](https://github.com/fritzmg/contao-multidomain-rebuild-index). I haven't made the extension compatible with Contao 4 though (if you need it at all), since the search indexing will be changed in a future Contao 4 version anyway.

**Comment by leofeyer** [comment] 2016-11-29 19:28
The extension should be compatible with Contao 4.

@contao/developers Should we handle this case or just wait for the crawler service?

**Comment by agoat** [comment] 2016-11-30 08:58
If the search indexing is changing in future version, I can live with that for now. 

Normally I deny any access to the contao backend on productive systems and give access from another subdomain. And I like to manage multiple pages with one contao installation. 

Maybe a easy temporary solution could be to add a field in the settings to enter all domains, wich will be set to Access-Control-Allow-Origin. Or to add all root page dns names automatically.

**Comment by leofeyer** [comment] 2016-12-14 15:01
As discussed in Mumble on December 14th, @Toflar is going to create a PR to fix this.

 * Add two additional headers to the Ajax request in `be_rebuild_index.html5`.
 * If there is a request with those headers, try to validate them.
 * If the headers are valid, set the `Access-Control-Allow-Origin` header.

**Comment by Toflar** [comment] 2016-12-14 15:08
Note to myself: should be done against 3.5.

**Comment by leofeyer** [comment] 2016-12-29 10:14
Closed in favor of #8597.

**Closed by leofeyer** 2016-12-29 10:14 UTC
Labels: defect

**Comment by agoat** [comment] 2017-04-07 10:17
For documentation: There as also a PR for Contao 4: https://github.com/contao/core-bundle/pull/689

**Comment by dibole** [comment] 2018-01-25 15:36
I still have this problem in Contao 4.4.9 
When trying to rebuild the search index in the backend, all other domains, than the one logged in, can´t be indexed. See [Forum](https://community.contao.org/de/showthread.php?69549-Suchindex-wird-im-Multidomainbetrieb-nicht-komplett-aufgebaut&p=462908#post462908)

**Comment by fritzmg** [comment] 2018-01-25 16:18
@dibole see the Forum: have you set a __Domain name__ for _all_ your website roots? Otherwise it will not work.

**Comment by dibole** [comment] 2018-01-25 16:59
Sure, in the website roots there are different domain names under DNS > Domainname

**Comment by fritzmg** [comment] 2018-01-25 17:00
I cannot reproduce your problem though. Building the search index over multiple domains works in Contao 4.4.12.
