### ISSUE TITLE
The front end preview does not work properly

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1033] opened 2017-08-20 13:38 UTC
As of version 4.4.3 the Contao front end preview always redirects to the start page (index page) no matter what article or page is being viewed.

To reproduce in the Contao online demo:
- Edit an article (e.g. "_Media elements_")
- Open the front end preview
- The preview shows the start page instead of the "_Media elements_" page

**Comment by leofeyer** [comment] 2017-08-20 16:15
That's another problem caused by the `ref=` parameter being added to the URL. It currently creates `preview?ref=VWCeDoxa?page=55` instead of `&page=55`.

**Comment by aschempp** [comment] 2017-08-20 21:25
What did we change in regards to the `ref=` parameter?

**Comment by xchs** [comment] 2017-08-20 21:29
Maybe this one: https://github.com/contao/core-bundle/commit/e66793480bb7c8b8f2fddf9a25d695c8b34f89c7

**Comment by leofeyer** [comment] 2017-08-21 08:05
Fixed in 800b1648cfa932dd74092799d24dd1275c342ffa.

**Closed by leofeyer** 2017-08-21 08:05 UTC
Labels: defect

**Comment by xchs** [comment] 2017-08-21 09:09
Thanks a lot. It now works as expected.

Can we also get rid of the `?referer=…` parameter that gets added to the URL when clicking on the back end link in the install tool? Or is this referer ID necessary for something that I don't see or know at the moment?

**Comment by leofeyer** [comment] 2017-08-22 13:16
The install tool link goes straight into the back end, so you don't have to log in if you are logged in already. If we changed it, the `?referer=` parameter would disappear from the URL but you would have to log in every time.

**Comment by xchs** [comment] 2017-08-22 13:19
Okay, thanks for the explanation. This makes sense, of course.

**Comment by leofeyer** [comment] 2017-08-22 13:31
Optimized in be3a365205a7583692ac870d0bf55ab6751a45de. 😄
