### ISSUE TITLE
Form field configuration issues

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1622] opened 2018-07-18 11:22 UTC
When you use a `text` form field and you set the validation to `numeric characters` (`digit`), you'll get an `<input type="number">` field. For those fields the `maxlength` attribute is ignored (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength) so it makes no sense to configure this. Instead, for this validation, `max` and `min` and even `pattern` would make sense.

**Comment by m-vo** [comment] 2018-07-18 11:53
I think in most cases it even does not make sense that it's output as `type="number"` because of the default rendering of this type with up/down arrows in the common browsers.

**Comment by fritzmg** [comment] 2018-07-18 12:07
> I think in most cases it even does not make sense that it's output as type="number" because of the default rendering of this type with up/down arrows in the common browsers.

That's not really a reason not to use `type="number"`? ;) You should always use the most specific semantics for your form fields. Just makes things easier for everyone (in theory).

**Comment by m-vo** [comment] 2018-07-18 12:13
Sure. The problem is the semantics: something can be a number but incrementing it does not necessarily make sense. I'd rather allow the type and pattern to be specified in the backend instead of hiding it under *validation*.

**Comment by leofeyer** [comment] 2018-08-31 15:03
Closed in favor of https://github.com/contao/contao/pull/25.

**Closed by leofeyer** 2018-08-31 15:03 UTC
Labels: feature
