### ISSUE TITLE
Buttons not visible depending on backend popup size

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#720] opened 2017-03-07 18:13 UTC
The save, save&close etc. buttons are not visible in a backend popup if the popup does not have sufficient size.

How to reproduce:
1. Create content element "image"
2. Select an image to open the popup
3. Switch to file manager
4. Create a new folder

The save etc. buttons are outside of `<form>` element due to `position:fixed`.

**Comment by leofeyer** [comment] 2017-03-17 16:13
I cannot reproduce this actually; the buttons do not have `position:fixed` in my installation. Are you using any third-party extensions such as sticky footer?

**Comment by aschempp** [comment] 2017-03-20 12:03
I do not. The `position: fixed` is from here: https://github.com/contao/core-bundle/blob/7f746f41156f81867aefbb812f5e086e543d5bdd/src/Resources/contao/themes/flexible/src/main.css#L381

**Comment by leofeyer** [comment] 2017-03-21 09:26
Still not able to reproduce:

![](https://cloud.githubusercontent.com/assets/1192057/24140556/cafdfe30-0e20-11e7-891e-711ce0fc3fc5.png)

Which browser are you using?

**Comment by aschempp** [comment] 2017-03-21 09:27
Safari

**Comment by leofeyer** [comment] 2017-03-21 10:54
No, I mean a real browser. 😄 But the issue occurs in Firefox, too, so …

**Comment by leofeyer** [comment] 2017-03-21 12:28
Fixed in 44135d8a0ac890681c6f77804c475bd7e4acf961.

**Closed by leofeyer** 2017-03-21 12:28 UTC
Labels: defect
